'use client';

import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2, Lock, Trophy, X, Zap, MessageCircle, Heart, CalendarCheck2, Info } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Def={id:string;name:string;description:string;category:string;icon:string|null;target:number};
type Progress={achievement_id:string;progress:number;unlocked_at:string|null};
type Profile={xp:number;level:number};
const labels:Record<string,string>={eventos:'🎟️ Eventos',conteudo:'✍️ Conteúdo',comunidade:'💬 Comunidade',social:'🤝 Social',lendas:'👑 Lendas'};
const order=['eventos','conteudo','comunidade','social','lendas'];
const TITLES=['Novato','Curioso Geek','Explorador','Player 1','Veterano','Especialista','Mestre Geek','Lenda','Ícone Geek','Deus Geek'];
const XP_ACTIONS=[
 {label:'Criar uma publicação',detail:'Texto, foto, vídeo ou Geek Card publicado no feed.',xp:20,icon:Zap},
 {label:'Comentar uma publicação',detail:'Participar das conversas da comunidade.',xp:10,icon:MessageCircle},
 {label:'Curtir uma publicação',detail:'Cada curtida válida contabilizada pelo sistema.',xp:2,icon:Heart},
 {label:'Confirmar participação em evento',detail:'Ao entrar na lista de participantes de um evento.',xp:15,icon:CalendarCheck2},
];

export function AchievementsClient(){
 const supabase=useMemo(()=>createClient(),[]); const [defs,setDefs]=useState<Def[]>([]); const [progress,setProgress]=useState<Record<string,Progress>>({}); const [profile,setProfile]=useState<Profile|null>(null); const [selected,setSelected]=useState<Def|null>(null); const [loading,setLoading]=useState(true);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.rpc('sync_user_achievements',{target_user:user.id});const [{data:d},{data:p},{data:pr}]=await Promise.all([supabase.from('achievement_definitions').select('*'),supabase.from('user_achievements').select('achievement_id,progress,unlocked_at').eq('user_id',user.id),supabase.from('profiles').select('xp,level').eq('id',user.id).maybeSingle()]);setDefs((d||[]) as Def[]);const map:Record<string,Progress>={};(p||[]).forEach((row:Progress)=>map[row.achievement_id]=row);setProgress(map);if(pr)setProfile({xp:Number(pr.xp||0),level:Number(pr.level||1)});setLoading(false)}
 useEffect(()=>{void load();},[supabase]);
 const unlocked=defs.filter(d=>!!progress[d.id]?.unlocked_at).length; const pct=defs.length?Math.round((unlocked/defs.length)*100):0;
 const level=Math.max(1,Math.min(10,profile?.level||1));const xp=profile?.xp||0;const currentLevelXp=level>=10?500:Math.max(0,xp-(level-1)*500);const remaining=level>=10?0:Math.max(0,level*500-xp);
 if(loading)return <div className="py-20 text-center text-slate-400">Carregando conquistas...</div>;
 return <div className="mx-auto max-w-5xl px-3 sm:px-4 pb-10">
  <div className="mb-5"><p className="text-sm font-bold text-geek-orange">GAMIFICAÇÃO</p><h1 className="text-2xl sm:text-3xl font-black">Conquistas e XP</h1><p className="mt-1 text-sm text-slate-400">Veja seu progresso e entenda exatamente o que faz você avançar no GeekoPlay.</p></div>

  <section className="mb-6 rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)] lg:items-center"><div><p className="text-sm text-slate-400">Seu nível atual</p><p className="mt-1 text-2xl font-black">Nível {level} · {TITLES[level-1]}</p><p className="mt-1 text-sm text-slate-500">{xp} XP total</p></div><div><div className="mb-2 flex justify-between gap-3 text-xs text-slate-400"><span>{level>=10?'Nível máximo':`${currentLevelXp} / 500 XP neste nível`}</span><span>{level>=10?'Deus Geek':`Faltam ${remaining} XP`}</span></div><div className="h-3 overflow-hidden rounded-full bg-geek-soft"><div className="h-full rounded-full bg-geek-orange transition-all" style={{width:`${level>=10?100:Math.min(100,(currentLevelXp/500)*100)}%`}}/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{TITLES.map((title,index)=><div key={title} className={`rounded-xl border px-2 py-2 text-center text-[11px] ${index+1===level?'border-orange-500/50 bg-orange-500/10 text-orange-300':'border-geek-line bg-geek-soft text-slate-500'}`}><b className="block">Nível {index+1}</b><span>{title}</span></div>)}</div></div></div></section>

  <section id="como-ganhar-xp" className="mb-6 rounded-2xl border border-orange-500/25 bg-orange-500/5 p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><Zap size={19}/></div><div><h2 className="text-lg font-black">Como ganhar XP?</h2><p className="mt-1 text-sm text-slate-400">Estas são as ações que atualmente geram XP automaticamente no GeekoPlay.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{XP_ACTIONS.map(action=>{const Icon=action.icon;return <div key={action.label} className="flex items-start gap-3 rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-geek-soft text-orange-300"><Icon size={18}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><b className="text-sm">{action.label}</b><span className="shrink-0 rounded-full bg-orange-500/10 px-2.5 py-1 text-xs font-bold text-orange-300">+{action.xp} XP</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{action.detail}</p></div></div>})}</div><div className="mt-4 flex items-start gap-2 rounded-xl border border-geek-line bg-geek-soft p-3 text-xs leading-5 text-slate-400"><Info size={16} className="mt-0.5 shrink-0 text-slate-500"/><p><b>Não geram XP:</b> editar nome, bio, cidade, trocar avatar/capa ou simplesmente navegar entre páginas. Assim o nível representa participação real, e não ações básicas de manutenção do perfil.</p></div></section>

  <section className="mb-6 rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-400">Conquistas desbloqueadas</p><p className="text-3xl font-black">{unlocked}<span className="text-lg text-slate-500">/{defs.length}</span></p></div><div className="min-w-0 flex-1 sm:max-w-xl"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>Progresso geral de conquistas</span><span>{pct}%</span></div><div className="h-3 overflow-hidden rounded-full bg-geek-soft"><div className="h-full rounded-full bg-geek-orange transition-all" style={{width:`${pct}%`}}/></div></div><Trophy size={40} className="text-yellow-400"/></div></section>
  <div className="space-y-7">{order.map(cat=>{const items=defs.filter(d=>d.category===cat);if(!items.length)return null;return <section key={cat}><h2 className="mb-3 text-lg font-black">{labels[cat]||cat}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(d=>{const p=progress[d.id];const current=Math.min(p?.progress||0,d.target);const done=!!p?.unlocked_at;const percent=Math.min(100,Math.round((current/d.target)*100));return <button key={d.id} onClick={()=>setSelected(d)} className={`text-left rounded-2xl border p-4 transition ${done?'border-orange-500/45 bg-orange-500/8':'border-geek-line bg-geek-panel hover:border-slate-600'}`}><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl text-xl ${done?'bg-orange-500/15':'bg-geek-soft grayscale'}`}>{d.icon||'🏅'}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate">{d.name}</b>{done?<CheckCircle2 size={16} className="shrink-0 text-green-400"/>:<Lock size={14} className="shrink-0 text-slate-500"/>}</div><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-400">{d.description}</p></div></div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[11px] text-slate-500"><span>{current}/{d.target}</span><span>{percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-geek-soft"><div className={`h-full rounded-full ${done?'bg-green-500':'bg-geek-orange'}`} style={{width:`${percent}%`}}/></div></div></button>})}</div></section>})}</div>
  {selected&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-3" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl border border-geek-line bg-geek-panel p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-orange-500/10 text-3xl">{selected.icon||'🏅'}</div><div><p className="text-xs font-bold uppercase tracking-wider text-orange-300">{labels[selected.category]||selected.category}</p><h3 className="text-xl font-black">{selected.name}</h3></div></div><button onClick={()=>setSelected(null)} className="rounded-xl p-2 hover:bg-geek-soft"><X size={20}/></button></div><p className="mt-5 text-sm leading-6 text-slate-300">{selected.description}</p>{(()=>{const p=progress[selected.id];const current=Math.min(p?.progress||0,selected.target);const done=!!p?.unlocked_at;const percent=Math.min(100,Math.round((current/selected.target)*100));return <div className="mt-5 rounded-2xl bg-geek-soft p-4"><div className="flex items-center justify-between text-sm"><span>{done?'Conquista desbloqueada':'Em andamento'}</span><b>{percent}%</b></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-black/25"><div className={`h-full ${done?'bg-green-500':'bg-geek-orange'}`} style={{width:`${percent}%`}}/></div>{done&&p?.unlocked_at&&<p className="mt-2 text-xs text-slate-500">Desbloqueada em {new Date(p.unlocked_at).toLocaleDateString('pt-BR')}</p>}</div>})()}</div></div>}
 </div>
}
