'use client';

import { useEffect,useMemo,useState } from 'react';
import { Award, CheckCircle2, Lock, Trophy, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Def={id:string;name:string;description:string;category:string;icon:string|null;target:number};
type Progress={achievement_id:string;progress:number;unlocked_at:string|null};
const labels:Record<string,string>={eventos:'🎟️ Eventos',conteudo:'✍️ Conteúdo',comunidade:'💬 Comunidade',social:'🤝 Social',lendas:'👑 Lendas'};
const order=['eventos','conteudo','comunidade','social','lendas'];

export function AchievementsClient(){
 const supabase=useMemo(()=>createClient(),[]); const [defs,setDefs]=useState<Def[]>([]); const [progress,setProgress]=useState<Record<string,Progress>>({}); const [selected,setSelected]=useState<Def|null>(null); const [loading,setLoading]=useState(true);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.rpc('sync_user_achievements',{target_user:user.id});const [{data:d},{data:p}]=await Promise.all([supabase.from('achievement_definitions').select('*'),supabase.from('user_achievements').select('achievement_id,progress,unlocked_at').eq('user_id',user.id)]);setDefs((d||[]) as Def[]);const map:Record<string,Progress>={};(p||[]).forEach((row:Progress)=>map[row.achievement_id]=row);setProgress(map);setLoading(false)}
 useEffect(()=>{void load();},[supabase]);
 const unlocked=defs.filter(d=>!!progress[d.id]?.unlocked_at).length; const pct=defs.length?Math.round((unlocked/defs.length)*100):0;
 if(loading)return <div className="py-20 text-center text-slate-400">Carregando conquistas...</div>;
 return <div className="mx-auto max-w-5xl px-3 sm:px-4 pb-10">
  <div className="mb-5"><p className="text-sm font-bold text-geek-orange">GAMIFICAÇÃO</p><h1 className="text-2xl sm:text-3xl font-black">Conquistas</h1><p className="mt-1 text-sm text-slate-400">Seu progresso é atualizado automaticamente conforme você usa o GeekoPlay.</p></div>
  <section className="mb-6 rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-slate-400">Desbloqueadas</p><p className="text-3xl font-black">{unlocked}<span className="text-lg text-slate-500">/{defs.length}</span></p></div><div className="min-w-0 flex-1 sm:max-w-xl"><div className="mb-2 flex justify-between text-xs text-slate-400"><span>Progresso geral</span><span>{pct}%</span></div><div className="h-3 overflow-hidden rounded-full bg-geek-soft"><div className="h-full rounded-full bg-geek-orange transition-all" style={{width:`${pct}%`}}/></div></div><Trophy size={40} className="text-yellow-400"/></div></section>
  <div className="space-y-7">{order.map(cat=>{const items=defs.filter(d=>d.category===cat);if(!items.length)return null;return <section key={cat}><h2 className="mb-3 text-lg font-black">{labels[cat]||cat}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(d=>{const p=progress[d.id];const current=Math.min(p?.progress||0,d.target);const done=!!p?.unlocked_at;const percent=Math.min(100,Math.round((current/d.target)*100));return <button key={d.id} onClick={()=>setSelected(d)} className={`text-left rounded-2xl border p-4 transition ${done?'border-orange-500/45 bg-orange-500/8':'border-geek-line bg-geek-panel hover:border-slate-600'}`}><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl text-xl ${done?'bg-orange-500/15':'bg-geek-soft grayscale'}`}>{d.icon||'🏅'}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate">{d.name}</b>{done?<CheckCircle2 size={16} className="shrink-0 text-green-400"/>:<Lock size={14} className="shrink-0 text-slate-500"/>}</div><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-400">{d.description}</p></div></div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[11px] text-slate-500"><span>{current}/{d.target}</span><span>{percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-geek-soft"><div className={`h-full rounded-full ${done?'bg-green-500':'bg-geek-orange'}`} style={{width:`${percent}%`}}/></div></div></button>})}</div></section>})}</div>
  {selected&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-3" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl border border-geek-line bg-geek-panel p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-orange-500/10 text-3xl">{selected.icon||'🏅'}</div><div><p className="text-xs font-bold uppercase tracking-wider text-orange-300">{labels[selected.category]||selected.category}</p><h3 className="text-xl font-black">{selected.name}</h3></div></div><button onClick={()=>setSelected(null)} className="rounded-xl p-2 hover:bg-geek-soft"><X size={20}/></button></div><p className="mt-5 text-sm leading-6 text-slate-300">{selected.description}</p>{(()=>{const p=progress[selected.id];const current=Math.min(p?.progress||0,selected.target);const done=!!p?.unlocked_at;const percent=Math.min(100,Math.round((current/selected.target)*100));return <div className="mt-5 rounded-2xl bg-geek-soft p-4"><div className="flex items-center justify-between text-sm"><span>{done?'Conquista desbloqueada':'Em andamento'}</span><b>{percent}%</b></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-black/25"><div className={`h-full ${done?'bg-green-500':'bg-geek-orange'}`} style={{width:`${percent}%`}}/></div>{done&&p?.unlocked_at&&<p className="mt-2 text-xs text-slate-500">Desbloqueada em {new Date(p.unlocked_at).toLocaleDateString('pt-BR')}</p>}</div>})()}</div></div>}
 </div>
}
