'use client';

import { useEffect,useMemo,useState } from 'react';
import { Copy, ExternalLink, X } from 'lucide-react';
import { usePathname } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

type Ad={id:string;title:string;description:string|null;image_url:string|null;cta_label:string|null;cta_url:string|null;ad_type:string;placement:string;audience:string;navigation_interval:number;cooldown_minutes:number;max_impressions_per_user_day:number;starts_at:string|null;ends_at:string|null;has_promo_code:boolean;promo_code:string|null;promo_instructions:string|null};

function todayKey(){return new Date().toISOString().slice(0,10)}

export function AdLayer(){
 const supabase=useMemo(()=>createClient(),[]);const pathname=usePathname();const [ad,setAd]=useState<Ad|null>(null);const [userId,setUserId]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user||cancelled)return;setUserId(user.id);const [{data:profile},{data:settings},{data:rows}]=await Promise.all([supabase.from('profiles').select('is_pro').eq('id',user.id).single(),supabase.from('monetization_settings').select('pro_hides_ads').eq('id','default').single(),supabase.from('ads').select('id,title,description,image_url,cta_label,cta_url,ad_type,placement,audience,navigation_interval,cooldown_minutes,max_impressions_per_user_day,starts_at,ends_at,has_promo_code,promo_code,promo_instructions').eq('active',true).order('created_at',{ascending:false})]);if(cancelled)return;if(profile?.is_pro&&settings?.pro_hides_ads){setAd(null);return}const now=Date.now();let nav=Number(localStorage.getItem('geekoplay_ad_nav')||'0')+1;localStorage.setItem('geekoplay_ad_nav',String(nav));const eligible=((rows||[]) as Ad[]).filter(a=>{if(a.audience==='pro'&&!profile?.is_pro)return false;if(a.audience==='non_pro'&&profile?.is_pro)return false;if(a.starts_at&&new Date(a.starts_at).getTime()>now)return false;if(a.ends_at&&new Date(a.ends_at).getTime()<now)return false;if(a.placement==='sponsored_feed'&&pathname!=='/')return false;if(nav%Math.max(1,a.navigation_interval)!==0)return false;const count=Number(localStorage.getItem(`geekoplay_ad_${a.id}_${todayKey()}_count`)||'0');if(count>=a.max_impressions_per_user_day)return false;const last=Number(localStorage.getItem(`geekoplay_ad_${a.id}_last`)||'0');if(last&&now-last<a.cooldown_minutes*60000)return false;return true});const selected=eligible[0]||null;setAd(selected);if(selected){localStorage.setItem(`geekoplay_ad_${selected.id}_${todayKey()}_count`,String(Number(localStorage.getItem(`geekoplay_ad_${selected.id}_${todayKey()}_count`)||'0')+1));localStorage.setItem(`geekoplay_ad_${selected.id}_last`,String(now));void supabase.from('ad_events').insert({ad_id:selected.id,user_id:user.id,event_type:'impression'})}})();return()=>{cancelled=true}},[pathname,supabase]);
 if(!ad)return null;
 async function click(){if(userId)void supabase.from('ad_events').insert({ad_id:ad!.id,user_id:userId,event_type:'click'});if(ad?.cta_url)window.open(ad.cta_url,'_blank','noopener,noreferrer')}
 async function copyCode(){if(ad?.promo_code)await navigator.clipboard.writeText(ad.promo_code)}
 const content=<div className="overflow-hidden rounded-2xl border border-orange-500/25 bg-[#171b22] shadow-2xl"><div className="relative flex max-h-72 min-h-24 w-full items-center justify-center overflow-hidden bg-black/30">{ad.image_url?<img src={ad.image_url} alt={ad.title} className="block h-auto max-h-72 w-auto max-w-full object-contain object-center"/>:<div className="p-8 text-sm text-slate-500">Conteúdo patrocinado</div>}<button onClick={()=>setAd(null)} className="absolute right-2 top-2 rounded-full bg-black/70 p-2 text-white" aria-label="Fechar anúncio"><X size={16}/></button></div><div className="p-4"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">Patrocinado</p><h3 className="mt-1 text-lg font-black">{ad.title}</h3>{ad.description&&<p className="mt-2 text-sm leading-6 text-slate-400">{ad.description}</p>}{ad.has_promo_code&&ad.promo_code&&<div className="mt-3 rounded-xl border border-geek-line bg-geek-soft p-3"><p className="text-[10px] uppercase text-slate-500">Código promocional</p><div className="mt-1 flex items-center justify-between gap-3"><b className="truncate text-orange-300">{ad.promo_code}</b><button onClick={copyCode} className="flex shrink-0 items-center gap-1 text-xs font-bold"><Copy size={14}/>Copiar</button></div>{ad.promo_instructions&&<p className="mt-1 text-xs text-slate-500">{ad.promo_instructions}</p>}</div>}{ad.cta_url&&<button onClick={click} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-geek-orange px-4 py-3 font-black">{ad.cta_label||'Saiba mais'}<ExternalLink size={16}/></button>}</div></div>;
 if(ad.placement==='sponsored_feed')return <div className="mx-auto mb-4 max-w-2xl px-3 sm:px-4">{content}</div>;
 if(ad.placement==='footer_banner')return <div className="fixed inset-x-3 bottom-20 z-[70] mx-auto max-w-2xl lg:bottom-4">{content}</div>;
 if(ad.placement==='bottom_sheet')return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/55 p-0 sm:p-4" onClick={()=>setAd(null)}><div className="w-full max-w-xl" onClick={e=>e.stopPropagation()}>{content}</div></div>;
 return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/65 p-3" onClick={()=>setAd(null)}><div className="w-full max-w-lg" onClick={e=>e.stopPropagation()}>{content}</div></div>;
}
