'use client';

import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2, Crown, DollarSign, Loader2, Megaphone, Rocket, Save, Settings2, XCircle } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Settings={premium_price:number;premium_payment_url:string|null;boost_price_per_day:number;boost_payment_url:string|null;pro_hides_ads:boolean};
type Profile={id:string;display_name:string;email:string|null;is_pro:boolean};
type Premium={id:string;user_id:string;amount:number;status:string;requested_at:string};
type Boost={id:string;user_id:string;post_id:string;days:number;amount:number;status:string;requested_at:string};
type AdMetric={event_type:string};
const tabs=['Visão Geral','Premium','Impulsionar','Anúncios','Config'] as const;

export function AdminMonetizationClient(){
 const supabase=useMemo(()=>createClient(),[]); const [tab,setTab]=useState<(typeof tabs)[number]>('Visão Geral'); const [settings,setSettings]=useState<Settings|null>(null); const [profiles,setProfiles]=useState<Record<string,Profile>>({}); const [premium,setPremium]=useState<Premium[]>([]); const [boosts,setBoosts]=useState<Boost[]>([]); const [adEvents,setAdEvents]=useState<AdMetric[]>([]); const [adsCount,setAdsCount]=useState(0); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 async function load(){setLoading(true);const [{data:s},{data:pr},{data:br},{data:pe},{data:ae},{count:ac}]=await Promise.all([supabase.from('monetization_settings').select('*').eq('id','default').single(),supabase.from('premium_requests').select('id,user_id,amount,status,requested_at').order('requested_at',{ascending:false}),supabase.from('boost_requests').select('id,user_id,post_id,days,amount,status,requested_at').order('requested_at',{ascending:false}),supabase.from('profiles').select('id,display_name,email,is_pro'),supabase.from('ad_events').select('event_type'),supabase.from('ads').select('id',{count:'exact',head:true})]);setSettings(s as Settings);setPremium((pr||[]) as Premium[]);setBoosts((br||[]) as Boost[]);const map:Record<string,Profile>={};(pe||[]).forEach((p:Profile)=>map[p.id]=p);setProfiles(map);setAdEvents((ae||[]) as AdMetric[]);setAdsCount(ac||0);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function setRequest(table:'premium_requests'|'boost_requests',id:string,status:'approved'|'rejected'){setMessage('');const {error}=await supabase.from(table).update({status}).eq('id',id);setMessage(error?'Não foi possível atualizar a solicitação.':status==='approved'?'Solicitação aprovada.':'Solicitação recusada.');await load()}
 async function saveSettings(){if(!settings)return;setSaving(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('monetization_settings').update({...settings,updated_at:new Date().toISOString(),updated_by:user?.id||null}).eq('id','default');setMessage(error?'Não foi possível salvar as configurações.':'Configurações salvas.');setSaving(false);await load()}
 if(loading)return <div className="grid place-items-center py-24"><Loader2 className="animate-spin text-geek-orange"/></div>;
 const pendingPremium=premium.filter(r=>r.status==='pending'); const pendingBoost=boosts.filter(r=>r.status==='pending'); const activePro=Object.values(profiles).filter(p=>p.is_pro).length; const impressions=adEvents.filter(e=>e.event_type==='impression').length; const clicks=adEvents.filter(e=>e.event_type==='click').length; const ctr=impressions?((clicks/impressions)*100).toFixed(1):'0.0'; const approvedRevenue=[...premium,...boosts].filter(r=>r.status==='approved').reduce((sum,r)=>sum+Number(r.amount||0),0);
 return <div className="mx-auto max-w-7xl space-y-5"><div><p className="text-sm font-bold text-geek-orange">ADMINISTRAÇÃO</p><h1 className="text-2xl font-black sm:text-3xl">Monetização</h1><p className="mt-2 text-sm text-slate-400">Premium, impulsionamentos, anúncios e configurações comerciais.</p></div><div className="overflow-x-auto pb-1"><div className="flex min-w-max gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${tab===t?'border-geek-orange bg-geek-orange text-white':'border-geek-line bg-geek-panel text-slate-300'}`}>{t}</button>)}</div></div>{message&&<div className="rounded-xl border border-geek-line bg-geek-panel p-3 text-sm text-slate-300">{message}</div>}
 {tab==='Visão Geral'&&<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[DollarSign,'Receita aprovada',approvedRevenue.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})],[Crown,'Premium ativos',String(activePro)],[Rocket,'Boosts pendentes',String(pendingBoost.length)],[Megaphone,'CTR de anúncios',`${ctr}%`]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-geek-line bg-geek-panel p-5"><Icon size={20} className="text-geek-orange"/><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>}
 {tab==='Premium'&&<section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Solicitações Premium</h2><p className="text-xs text-slate-500">{pendingPremium.length} pendente(s)</p></div><Crown className="text-yellow-400"/></div><div className="grid gap-3">{premium.length===0?<p className="py-8 text-center text-slate-500">Nenhuma solicitação Premium.</p>:premium.map(r=>{const p=profiles[r.user_id];return <div key={r.id} className="rounded-xl border border-geek-line bg-geek-bg p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b>{p?.display_name||'Usuário'}</b><p className="text-xs text-slate-500 break-all">{p?.email||r.user_id}</p><p className="mt-1 text-xs text-slate-400">{Number(r.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · {new Date(r.requested_at).toLocaleString('pt-BR')}</p></div><div className="flex items-center gap-2">{r.status==='pending'?<><button onClick={()=>setRequest('premium_requests',r.id,'approved')} className="flex items-center gap-1 rounded-lg bg-green-500/15 px-3 py-2 text-xs font-bold text-green-300"><CheckCircle2 size={15}/>Aprovar</button><button onClick={()=>setRequest('premium_requests',r.id,'rejected')} className="flex items-center gap-1 rounded-lg bg-red-500/10 px-3 py-2 text-xs font-bold text-red-300"><XCircle size={15}/>Recusar</button></>:<span className={`rounded-full px-2 py-1 text-xs ${r.status==='approved'?'bg-green-500/10 text-green-300':'bg-slate-500/10 text-slate-400'}`}>{r.status==='approved'?'Aprovado':r.status==='rejected'?'Recusado':'Cancelado'}</span>}</div></div></div>})}</div></section>}
 {tab==='Impulsionar'&&<section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Solicitações de impulsionamento</h2><p className="text-xs text-slate-500">Ao aprovar, o post recebe destaque pelo período solicitado.</p></div><Rocket className="text-geek-orange"/></div><div className="grid gap-3">{boosts.length===0?<p className="py-8 text-center text-slate-500">Nenhuma solicitação de impulsionamento.</p>:boosts.map(r=>{const p=profiles[r.user_id];return <div key={r.id} className="rounded-xl border border-geek-line bg-geek-bg p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b>{p?.display_name||'Usuário'}</b><p className="text-xs text-slate-500">{r.days} {r.days===1?'dia':'dias'} · {Number(r.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p><p className="mt-1 max-w-md truncate text-[10px] text-slate-600">Post: {r.post_id}</p></div>{r.status==='pending'?<div className="flex gap-2"><button onClick={()=>setRequest('boost_requests',r.id,'approved')} className="rounded-lg bg-green-500/15 px-3 py-2 text-xs font-bold text-green-300">Aprovar</button><button onClick={()=>setRequest('boost_requests',r.id,'rejected')} className="rounded-lg bg-red-500/10 px-3 py-2 text-xs font-bold text-red-300">Recusar</button></div>:<span className={`rounded-full px-2 py-1 text-xs ${r.status==='approved'?'bg-green-500/10 text-green-300':'bg-slate-500/10 text-slate-400'}`}>{r.status==='approved'?'Aprovado':r.status==='rejected'?'Recusado':'Cancelado'}</span>}</div></div>})}</div></section>}
 {tab==='Anúncios'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Anúncios cadastrados',adsCount],['Impressões',impressions],['Cliques',clicks],['CTR',`${ctr}%`]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-geek-line bg-geek-panel p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div>}
 {tab==='Config'&&settings&&<section className="max-w-3xl rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><Settings2 size={20} className="text-geek-orange"/><h2 className="font-black">Configurações comerciais</h2></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Preço Premium (R$)<input type="number" min="0" step="0.01" value={settings.premium_price} onChange={e=>setSettings({...settings,premium_price:Number(e.target.value)})} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label><label className="grid gap-1 text-sm">Preço do boost por dia (R$)<input type="number" min="0" step="0.01" value={settings.boost_price_per_day} onChange={e=>setSettings({...settings,boost_price_per_day:Number(e.target.value)})} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label><label className="grid gap-1 text-sm sm:col-span-2">Link de pagamento Premium<input value={settings.premium_payment_url||''} onChange={e=>setSettings({...settings,premium_payment_url:e.target.value||null})} placeholder="https://..." className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label><label className="grid gap-1 text-sm sm:col-span-2">Link de pagamento Impulsionar<input value={settings.boost_payment_url||''} onChange={e=>setSettings({...settings,boost_payment_url:e.target.value||null})} placeholder="https://..." className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label><label className="flex items-center gap-3 rounded-xl border border-geek-line bg-geek-soft p-3 text-sm sm:col-span-2"><input type="checkbox" checked={settings.pro_hides_ads} onChange={e=>setSettings({...settings,pro_hides_ads:e.target.checked})}/><span>Usuários PRO não recebem anúncios</span></label></div><button onClick={saveSettings} disabled={saving} className="mt-4 flex items-center gap-2 rounded-xl bg-geek-orange px-4 py-3 font-black disabled:opacity-60"><Save size={17}/>{saving?'Salvando...':'Salvar configurações'}</button></section>}
 </div>
}
