'use client';

import { useMemo,useState } from 'react';
import { Search,Store,Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Item={id:string;seller_id:string;title:string;description:string|null;image_urls:string[];price:number;category:string|null;item_condition:string|null;city:string|null;state:string|null;whatsapp:string|null;instagram:string|null;status:string;created_at:string};
type Seller={id:string;display_name:string;username:string|null};

const statusLabel:Record<string,string>={available:'Disponível',reserved:'Reservado',sold:'Vendido'};

export function AdminMarketClient({initialItems,sellers}:{initialItems:Item[];sellers:Seller[]}){
 const supabase=useMemo(()=>createClient(),[]);const [items,setItems]=useState(initialItems);const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
 const sellerMap=useMemo(()=>new Map(sellers.map(seller=>[seller.id,seller])),[sellers]);
 const visible=items.filter(item=>{const term=search.trim().toLowerCase();const matchesStatus=filter==='all'||item.status===filter;const seller=sellerMap.get(item.seller_id);const matchesText=!term||[item.title,item.description,item.category,item.city,item.state,seller?.display_name,seller?.username].some(value=>value?.toLowerCase().includes(term));return matchesStatus&&matchesText});
 const counts={total:items.length,available:items.filter(item=>item.status==='available').length,reserved:items.filter(item=>item.status==='reserved').length,sold:items.filter(item=>item.status==='sold').length};

 async function changeStatus(item:Item,status:string){setBusy(item.id);setMessage('');const {error}=await supabase.from('market_items').update({status,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)setMessage('Não foi possível atualizar o status deste anúncio.');else setItems(current=>current.map(row=>row.id===item.id?{...row,status}:row));setBusy(null)}
 function storagePath(url:string){const marker='/storage/v1/object/public/market/';const index=url.indexOf(marker);if(index<0)return null;try{return decodeURIComponent(url.slice(index+marker.length))}catch{return null}}
 async function remove(item:Item){if(!window.confirm(`Excluir permanentemente o anúncio “${item.title}”?`))return;setBusy(item.id);setMessage('');const {error}=await supabase.from('market_items').delete().eq('id',item.id);if(error){setMessage('Não foi possível excluir este anúncio.');setBusy(null);return}const paths=(item.image_urls||[]).map(storagePath).filter((path):path is string=>Boolean(path));if(paths.length)await supabase.storage.from('market').remove(paths);setItems(current=>current.filter(row=>row.id!==item.id));setBusy(null)}

 return <div className="space-y-5">
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Total" value={counts.total}/><Metric label="Disponíveis" value={counts.available}/><Metric label="Reservados" value={counts.reserved}/><Metric label="Vendidos" value={counts.sold}/></section>
  <section className="grid gap-2 rounded-2xl border border-geek-line bg-geek-panel p-3 sm:grid-cols-[minmax(0,1fr)_220px]"><label className="flex min-w-0 items-center gap-2 rounded-xl border border-geek-line bg-geek-soft px-3"><Search size={16} className="shrink-0 text-slate-500"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar item, vendedor ou cidade" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></label><select value={filter} onChange={event=>setFilter(event.target.value)} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-3 text-sm"><option value="all">Todos os status</option><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></select></section>
  {message&&<p className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{message}</p>}
  {visible.length===0?<div className="rounded-2xl border border-dashed border-geek-line bg-geek-panel p-10 text-center text-slate-400"><Store className="mx-auto mb-3 text-geek-orange"/>Nenhum anúncio encontrado.</div>:<section className="grid gap-3">{visible.map(item=>{const seller=sellerMap.get(item.seller_id);return <article key={item.id} className="grid gap-4 rounded-2xl border border-geek-line bg-geek-panel p-4 sm:grid-cols-[112px_minmax(0,1fr)] sm:p-5"><div className="flex aspect-[4/3] items-center justify-center overflow-hidden rounded-xl bg-black/25 sm:aspect-auto sm:h-24">{item.image_urls?.[0]?<img src={item.image_urls[0]} alt={item.title} className="block h-auto max-h-full w-auto max-w-full object-contain"/>:<Store className="text-slate-600"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-start gap-2"><div className="min-w-0 flex-1"><h2 className="truncate font-black">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{seller?.display_name||'Vendedor'}{seller?.username?` · @${seller.username}`:''} · {new Date(item.created_at).toLocaleDateString('pt-BR')}</p></div><b className="whitespace-nowrap text-geek-orange">{Number(item.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></div><p className="mt-2 line-clamp-2 text-sm text-slate-400">{item.description||'Sem descrição'}</p><p className="mt-2 text-xs text-slate-500">{[item.category,item.item_condition,[item.city,item.state].filter(Boolean).join(' / ')].filter(Boolean).join(' · ')}</p><div className="mt-4 flex flex-wrap items-center gap-2"><select value={item.status} onChange={event=>void changeStatus(item,event.target.value)} disabled={busy===item.id} aria-label={`Status de ${item.title}`} className="min-w-40 rounded-xl border border-geek-line bg-geek-soft px-3 py-2 text-sm disabled:opacity-50"><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></select><span className={`rounded-full px-2.5 py-1 text-xs ${item.status==='sold'?'bg-red-500/10 text-red-300':item.status==='reserved'?'bg-yellow-500/10 text-yellow-300':'bg-emerald-500/10 text-emerald-300'}`}>{statusLabel[item.status]||item.status}</span><a href={`/mercado/${item.id}`} className="rounded-xl border border-geek-line px-3 py-2 text-sm hover:bg-geek-soft">Ver anúncio</a><button onClick={()=>void remove(item)} disabled={busy===item.id} className="ml-auto flex items-center gap-2 rounded-xl border border-red-500/30 px-3 py-2 text-sm text-red-300 disabled:opacity-50"><Trash2 size={15}/>Excluir</button></div></div></article>})}</section>}
 </div>
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-geek-line bg-geek-panel p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
