'use client';

import { useEffect,useMemo,useState } from 'react';
import { ExternalLink, Loader2, Plus, RefreshCw, Rss, Save, Trash2, WandSparkles } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type News={id:string;title:string;summary:string|null;image_url:string|null;source_name:string|null;source_url:string;category:string|null;published_at:string|null;active:boolean;created_at:string;created_by:string|null};
type Source={id:string;name:string;domain:string|null;search_query:string;category:string;priority:number;active:boolean;created_at:string};
const categories=['Games','Anime','HQs & Comics','Filmes','Séries','Cosplay','Mangá','K-Pop','RPG','Tecnologia','Colecionáveis'];
const blank={title:'',summary:'',image_url:'',source_name:'',source_url:'',category:'Games',active:true};
const sourceBlank={name:'',domain:'',search_query:'',category:'Games',priority:100,active:true};

export function AdminNewsClient(){
 const supabase=useMemo(()=>createClient(),[]);
 const [rows,setRows]=useState<News[]>([]);
 const [sources,setSources]=useState<Source[]>([]);
 const [form,setForm]=useState<any>(blank);
 const [sourceForm,setSourceForm]=useState<any>(sourceBlank);
 const [loading,setLoading]=useState(true);
 const [extracting,setExtracting]=useState(false);
 const [refreshing,setRefreshing]=useState(false);
 const [savingSource,setSavingSource]=useState(false);
 const [message,setMessage]=useState('');
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const setSource=(k:string,v:any)=>setSourceForm((f:any)=>({...f,[k]:v}));

 async function load(){setLoading(true);const [{data:newsRows},{data:sourceRows}]=await Promise.all([supabase.from('news').select('*').order('published_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(300),supabase.from('news_sources').select('*').order('priority',{ascending:true}).order('created_at',{ascending:true})]);setRows((newsRows||[]) as News[]);setSources((sourceRows||[]) as Source[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);

 async function extract(){setMessage('');setExtracting(true);try{const r=await fetch('/api/admin/extract-news',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:form.source_url})});const j=await r.json();if(!r.ok)setMessage(j.error||'Não foi possível extrair os dados.');else setForm((f:any)=>({...f,...j}))}catch{setMessage('Não foi possível extrair os dados.')}finally{setExtracting(false)}}
 async function save(){const {data:{user}}=await supabase.auth.getUser();if(!user||!form.title.trim()||!form.source_url.trim()){setMessage('Preencha ao menos o link e o título.');return}const {error}=await supabase.from('news').insert({title:form.title.trim(),summary:form.summary.trim()||null,image_url:form.image_url.trim()||null,source_name:form.source_name.trim()||null,source_url:form.source_url.trim(),category:form.category||null,published_at:new Date().toISOString(),active:Boolean(form.active),created_by:user.id});if(error){setMessage('Não foi possível publicar a notícia.');return}setForm(blank);setMessage('Notícia publicada com crédito e link para a fonte original.');await load()}
 async function toggle(n:News){await supabase.from('news').update({active:!n.active}).eq('id',n.id);await load()}
 async function remove(id:string){if(!confirm('Excluir esta notícia?'))return;await supabase.from('news').delete().eq('id',id);await load()}

 async function addSource(){setMessage('');if(sourceForm.name.trim().length<2||sourceForm.search_query.trim().length<2){setMessage('Informe um nome e os termos de busca da fonte.');return}setSavingSource(true);const cleanDomain=sourceForm.domain.trim().replace(/^https?:\/\//,'').replace(/\/.*$/,'').replace(/^www\./,'');const {error}=await supabase.from('news_sources').insert({name:sourceForm.name.trim(),domain:cleanDomain||null,search_query:sourceForm.search_query.trim(),category:sourceForm.category,priority:Number(sourceForm.priority)||100,active:Boolean(sourceForm.active)});setSavingSource(false);if(error){setMessage('Não foi possível adicionar esta fonte. Verifique se ela já existe.');return}setSourceForm(sourceBlank);setMessage('Fonte adicionada. Ela passará a participar das próximas atualizações automáticas.');await load()}
 async function toggleSource(source:Source){await supabase.from('news_sources').update({active:!source.active,updated_at:new Date().toISOString()}).eq('id',source.id);await load()}
 async function deleteSource(source:Source){if(!confirm(`Remover a fonte "${source.name}"?`))return;await supabase.from('news_sources').delete().eq('id',source.id);await load()}
 async function refreshNow(){setRefreshing(true);setMessage('');const {data,error}=await supabase.rpc('admin_refresh_geek_news');setRefreshing(false);if(error){setMessage('Não foi possível atualizar as notícias agora.');return}setMessage(`${Number(data||0)} nova${Number(data||0)===1?' notícia':'s notícias'} encontrada${Number(data||0)===1?'':'s'} nesta atualização.`);await load()}

 const autoCount=rows.filter(n=>!n.created_by).length;const manualCount=rows.filter(n=>!!n.created_by).length;
 return <div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-bold text-geek-orange">ADMINISTRAÇÃO</p><h1 className="text-2xl font-black sm:text-3xl">Notícias</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">O GeekoPlay busca notícias automaticamente por temas e fontes configuradas. Toda notícia mantém o nome da fonte e o link original.</p></div><button onClick={()=>void refreshNow()} disabled={refreshing} className="inline-flex items-center justify-center gap-2 rounded-xl border border-orange-500/30 bg-orange-500/10 px-4 py-3 text-sm font-black text-orange-200 disabled:opacity-50">{refreshing?<Loader2 size={17} className="animate-spin"/>:<RefreshCw size={17}/>}Buscar notícias agora</button></div>

  {message&&<div className="rounded-xl border border-geek-line bg-geek-panel px-4 py-3 text-sm text-slate-300">{message}</div>}

  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-6"><div className="flex items-center gap-2"><Rss className="text-geek-orange"/><div><h2 className="font-black">Fontes automáticas</h2><p className="text-xs text-slate-500">A atualização roda automaticamente a cada 4 horas. Use domínio para priorizar um site específico ou deixe vazio para buscar as melhores fontes daquele tema.</p></div></div>
   <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><input value={sourceForm.name} onChange={e=>setSource('name',e.target.value)} placeholder="Nome da regra/fonte" className="rounded-xl border border-geek-line bg-geek-soft p-3 xl:col-span-2"/><input value={sourceForm.domain} onChange={e=>setSource('domain',e.target.value)} placeholder="Domínio opcional: omelete.com.br" className="rounded-xl border border-geek-line bg-geek-soft p-3 xl:col-span-2"/><select value={sourceForm.category} onChange={e=>setSource('category',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3">{categories.map(c=><option key={c}>{c}</option>)}</select><input type="number" min={1} max={1000} value={sourceForm.priority} onChange={e=>setSource('priority',Number(e.target.value))} placeholder="Prioridade" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={sourceForm.search_query} onChange={e=>setSource('search_query',e.target.value)} placeholder="Termos de busca: Nintendo Switch 2 games Brasil" className="rounded-xl border border-geek-line bg-geek-soft p-3 md:col-span-2 xl:col-span-5"/><button onClick={()=>void addSource()} disabled={savingSource} className="flex items-center justify-center gap-2 rounded-xl bg-geek-orange px-4 py-3 font-black disabled:opacity-50">{savingSource?<Loader2 size={17} className="animate-spin"/>:<Plus size={17}/>}Adicionar fonte</button></div>
   <div className="mt-5 grid gap-2">{sources.map(source=><article key={source.id} className="flex flex-col gap-3 rounded-xl border border-geek-line bg-geek-soft p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="truncate text-sm">{source.name}</b><span className="rounded-full bg-orange-500/10 px-2 py-0.5 text-[10px] text-orange-300">{source.category}</span>{source.domain&&<span className="rounded-full bg-cyan-500/10 px-2 py-0.5 text-[10px] text-cyan-300">{source.domain}</span>}</div><p className="mt-1 truncate text-xs text-slate-500">Busca: {source.search_query} · prioridade {source.priority}</p></div><div className="flex gap-2"><button onClick={()=>void toggleSource(source)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${source.active?'border-emerald-500/30 text-emerald-300':'border-geek-line text-slate-400'}`}>{source.active?'Ativa':'Pausada'}</button><button onClick={()=>void deleteSource(source)} className="rounded-lg border border-red-500/25 p-2 text-red-300" aria-label="Excluir fonte"><Trash2 size={15}/></button></div></article>)}</div>
  </section>

  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-6"><h2 className="font-black">Publicar manualmente</h2><p className="mt-1 text-xs text-slate-500">Cole uma URL, deixe o GeekoPlay preencher os dados, revise e publique.</p><div className="mt-4 grid gap-3"><div className="flex flex-col gap-2 sm:flex-row"><input value={form.source_url} onChange={e=>set('source_url',e.target.value)} placeholder="https://site.com/noticia" className="min-w-0 flex-1 rounded-xl border border-geek-line bg-geek-soft p-3"/><button onClick={()=>void extract()} disabled={extracting||!form.source_url.trim()} className="flex items-center justify-center gap-2 rounded-xl border border-geek-line px-4 text-sm disabled:opacity-40">{extracting?<Loader2 className="animate-spin" size={17}/>:<WandSparkles size={17}/>}Preencher</button></div><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Título" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><textarea value={form.summary} onChange={e=>set('summary',e.target.value)} placeholder="Resumo" className="min-h-24 rounded-xl border border-geek-line bg-geek-soft p-3"/><div className="grid gap-3 sm:grid-cols-2"><input value={form.source_name} onChange={e=>set('source_name',e.target.value)} placeholder="Fonte" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><select value={form.category} onChange={e=>set('category',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3">{categories.map(c=><option key={c}>{c}</option>)}</select></div><input value={form.image_url} onChange={e=>set('image_url',e.target.value)} placeholder="URL da imagem" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>set('active',e.target.checked)}/> Publicar imediatamente</label></div><button onClick={()=>void save()} className="mt-4 flex items-center gap-2 rounded-xl bg-geek-orange px-5 py-3 font-bold"><Save size={17}/>Publicar notícia</button></section>

  <section><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-black">Notícias cadastradas</h2><p className="text-xs text-slate-500">{autoCount} automáticas · {manualCount} manuais</p></div></div><div className="grid gap-3">{loading?<div className="grid place-items-center py-10"><Loader2 className="animate-spin"/></div>:rows.map(n=><article key={n.id} className="rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[10px] ${n.created_by?'bg-purple-500/10 text-purple-300':'bg-cyan-500/10 text-cyan-300'}`}>{n.created_by?'Manual':'Automática'}</span>{n.category&&<span className="rounded-full bg-orange-500/10 px-2 py-0.5 text-[10px] text-orange-300">{n.category}</span>}</div><b className="mt-2 block leading-snug">{n.title}</b><p className="mt-1 text-xs text-slate-500">Crédito: {n.source_name||'Fonte não informada'}{n.published_at?` · ${new Date(n.published_at).toLocaleString('pt-BR')}`:''}</p>{n.summary&&<p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-400">{n.summary}</p>}</div><div className="flex shrink-0 flex-wrap gap-2"><a href={n.source_url} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-xl border border-geek-line px-3 py-2 text-xs"><ExternalLink size={14}/>Fonte</a><button onClick={()=>void toggle(n)} className={`rounded-xl border px-3 py-2 text-xs ${n.active?'border-emerald-500/30 text-emerald-300':'border-geek-line text-slate-400'}`}>{n.active?'Ativa':'Inativa'}</button><button onClick={()=>void remove(n.id)} className="rounded-xl border border-red-500/30 p-2 text-red-300"><Trash2 size={16}/></button></div></div></article>)}</div></section>
 </div>;
}
