'use client';

import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2, Crown, DollarSign, Loader2, Megaphone, Rocket, Save, Settings2, XCircle } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Settings={premium_price:number;premium_payment_url:string|null;premium_duration_days:number;premium_period_label:string;boost_price_per_day:number;boost_payment_url:string|null;pro_hides_ads:boolean};
type Profile={id:string;display_name:string;email:string|null;is_pro:boolean;pro_expires_at:string|null};
type Premium={id:string;user_id:string;amount:number;status:string;requested_at:string;duration_days:number|null;period_label:string|null;starts_at:string|null;expires_at:string|null};
type Boost={id:string;user_id:string;post_id:string;days:number;amount:number;status:string;requested_at:string};
type AdMetric={event_type:string};
const tabs=['Visão Geral','Premium','Impulsionar','Anúncios','Config'] as const;
function fmtDate(value:string|null){return value?new Date(value).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}):null}

export function AdminMonetizationClient(){
 const supabase=useMemo(()=>createClient(),[]); const [tab,setTab]=useState<(typeof tabs)[number]>('Visão Geral'); const [settings,setSettings]=useState<Settings|null>(null); const [profiles,setProfiles]=useState<Record<string,Profile>>({}); const [premium,setPremium]=useState<Premium[]>([]); const [boosts,setBoosts]=useState<Boost[]>([]); const [adEvents,setAdEvents]=useState<AdMetric[]>([]); const [adsCount,setAdsCount]=useState(0); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 async function load(){setLoading(true);const [{data:s},{data:pr},{data:br},{data:pe},{data:ae},{count:ac}]=await Promise.all([supabase.from('monetization_settings').select('*').eq('id','default').single(),supabase.from('premium_requests').select('id,user_id,amount,status,requested_at,duration_days,period_label,starts_at,expires_at').order('requested_at',{ascending:false}),supabase.from('boost_requests').select('id,user_id,post_id,days,amount,status,requested_at').order('requested_at',{ascending:false}),supabase.from('profiles').select('id,display_name,email,is_pro,pro_expires_at'),supabase.from('ad_events').select('event_type'),supabase.from('ads').select('id',{count:'exact',head:true})]);setSettings(s as Settings);setPremium((pr||[]) as Premium[]);setBoosts((br||[]) as Boost[]);const map:Record<string,Profile>={};(pe||[]).forEach((p:Profile)=>map[p.id]=p);setProfiles(map);setAdEvents((ae||[]) as AdMetric[]);setAdsCount(ac||0);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function setRequest(table:'premium_requests'|'boost_requests',id:string,status:'approved'|'rejected'){setMessage('');const {error}=await supabase.from(table).update({status}).eq('id',id);setMessage(error?'Não foi possível atualizar a solicitação.':status==='approved'?'Solicitação aprovada.':'Solicitação recusada.');await load()}
 async function saveSettings(){if(!settings)return;setSaving(true);setMessage('');const {data:{user}}=await supabase.auth.getUser();const clean={...settings,premium_duration_days:Math.max(1,Math.min(3650,Number(settings.premium_duration_days)||30)),premium_period_label:(settings.premium_period_label||'Mensal').trim()||'Mensal',updated_at:new Date().toISOString(),updated_by:user?.id||null};const {error}=await supabase.from('monetization_settings').update(clean).eq('id','default');setMessage(error?'Não foi possível salvar as configurações.':'Configurações salvas.');setSaving(false);await load()}
 if(loading)return <div className="grid place-items-center py-24"><Loader2 className="animate-spin text-geek-orange"/></div>;
 const pendingPremium=premium.filter(r=>r.status==='pending'); const pendingBoost=boosts.filter(r=>r.status==='pending'); const activePro=Object.values(profiles).filter(p=>p.is_pro).length; const impressions=adEvents.filter(e=>e.event_type==='impression').length; const clicks=adEvents.filter(e=>e.event_type==='click').length; const ctr=impressions?((clicks/impressions)*100).toFixed(1):'0.0'; const approvedRevenue=[...premium,...boosts].filter(r=>r.status==='approved').reduce((sum,r)=>sum+Number(r.amount||0),0);
 return <div className="mx-auto max-w-7xl space-y-5"><div><p className="text-sm font-semibold text-geek-orange">ADMINISTRAÇÃO</p><h1 className="text-2xl font-semibold sm:text-3xl">Monetização</h1><p className="mt-2 text-sm text-slate-400">Premium, impulsionamentos, anúncios e configurações comerciais.</p></div><div className="overflow-x-auto pb-1"><div className="flex min-w-max gap-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl border px-4 py-2 text-sm font-semibold ${tab===t?'border-geek-orange bg-geek-orange text-white':'border-geek-line bg-geek-panel text-slate-300'}`}>{t}</button>)}</div></div>{message&&<div className="rounded-xl border border-geek-line bg-geek-panel p-3 text-sm text-slate-300">{message}</div>}
 {tab==='Visão Geral'&&<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[DollarSign,'Receita aprovada',approvedRevenue.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})],[Crown,'Premium ativos',String(activePro)],[Rocket,'Boosts pendentes',String(pendingBoost.length)],[Megaphone,'CTR de anúncios',`${ctr}%`]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-geek-line bg-geek-panel p-5"><Icon size={20} className="text-geek-orange"/><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>}
 {tab==='Premium'&&<section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Solicitações Premium</h2><p className="text-xs text-slate-500">{pendingPremium.length} pendente(s)</p></div><Crown className="text-yellow-400"/></div><div className="grid gap-3">{premium.length===0?<p className="py-8 text-center text-slate-500">Nenhuma solicitação Premium.</p>:premium.map(r=>{const p=profiles[r.user_id];return <div key={r.id} className="rounded-xl border border-geek-line bg-geek-bg p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="font-semibold">{p?.display_name||'Usuário'}</b><p className="break-all text-xs text-slate-500">{p?.email||r.user_id}</p><p className="mt-1 text-xs text-slate-400">{Number(r.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · {r.period_label||settings?.premium_period_label||'Plano'} · {r.duration_days||settings?.premium_duration_days||30} dias</p><p className="mt-1 text-[11px] text-slate-500">Pedido: {new Date(r.requested_at).toLocaleString('pt-BR')}{r.expires_at?` · Expira: ${fmtDate(r.expires_at)}`:''}{p?.is_pro&&p.pro_expires_at?` · PRO atual até: ${fmtDate(p.pro_expires_at)}`:''}</p></div><div className="flex items-center gap-2">{r.status==='pending'?<><button onClick={()=>setRequest('premium_requests',r.id,'approved')} className="flex items-center gap-1 rounded-lg bg-green-500/15 px-3 py-2 text-xs font-semibold text-green-300"><CheckCircle2 size={15}/>Aprovar</button><button onClick={()=>setRequest('premium_requests',r.id,'rejected')} className="flex items-center gap-1 rounded-lg bg-red-500/10 px-3 py-2 text-xs font-semibold text-red-300"><XCircle size={15}/>Recusar</button></>:<span className={`rounded-full px-2 py-1 text-xs ${r.status==='approved'?'bg-green-500/10 text-green-300':'bg-slate-500/10 text-slate-400'}`}>{r.status==='approved'?'Aprovado':r.status==='rejected'?'Recusado':'Cancelado'}</span>}</div></div></div>})}</div></section>}
 {tab==='Impulsionar'&&<section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Solicitações de impulsionamento</h2><p className="text-xs text-slate-500">Ao aprovar, o post recebe destaque pelo período solicitado.</p></div><Rocket className="text-geek-orange"/></div><div className="grid gap-3">{boosts.length===0?<p className="py-8 text-center text-slate-500">Nenhuma solicitação de impulsionamento.</p>:boosts.map(r=>{const p=profiles[r.user_id];return <div key={r.id} className="rounded-xl border border-geek-line bg-geek-bg p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="font-semibold">{p?.display_name||'Usuário'}</b><p className="text-xs text-slate-500">{r.days} {r.days===1?'dia':'dias'} · {Number(r.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p><p className="mt-1 max-w-md truncate text-[10px] text-slate-600">Post: {r.post_id}</p></div>{r.status==='pending'?<div className="flex gap-2"><button onClick={()=>setRequest('boost_requests',r.id,'approved')} className="rounded-lg bg-green-500/15 px-3 py-2 text-xs font-semibold text-green-300">Aprovar</button><button onClick={()=>setRequest('boost_requests',r.id,'rejected')} className="rounded-lg bg-red-500/10 px-3 py-2 text-xs font-semibold text-red-300">Recusar</button></div>:<span className={`rounded-full px-2 py-1 text-xs ${r.status==='approved'?'bg-green-500/10 text-green-300':'bg-slate-500/10 text-slate-400'}`}>{r.status==='approved'?'Aprovado':r.status==='rejected'?'Recusado':'Cancelado'}</span>}</div></div>})}</div></section>}
 {tab==='Anúncios'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Anúncios cadastrados',adsCount],['Impressões',impressions],['Cliques',clicks],['CTR',`${ctr}%`]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-geek-line bg-geek-panel p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>}
 {tab==='Config'&&settings&&<div className="max-w-4xl space-y-4">
  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5">
    <div className="mb-4 flex items-center gap-2"><Crown size={20} className="text-yellow-400"/><div><h2 className="font-semibold">Configurações Premium</h2><p className="text-xs text-slate-500">Esses campos controlam somente a assinatura PRO. Não interferem no impulsionamento.</p></div></div>
    <div className="grid gap-4 sm:grid-cols-2">
      <label className="grid gap-1 text-sm">Preço Premium (R$)<input type="number" min="0" step="0.01" value={settings.premium_price} onChange={e=>setSettings({...settings,premium_price:Number(e.target.value)})} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label>
      <label className="grid gap-1 text-sm">Nome do período<input value={settings.premium_period_label||''} maxLength={40} onChange={e=>setSettings({...settings,premium_period_label:e.target.value})} placeholder="Ex.: Mensal" className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/><span className="text-[10px] text-slate-500">Ex.: Mensal, Trimestral, Semestral ou Anual.</span></label>
      <label className="grid gap-1 text-sm sm:col-span-2">Duração do PRO (dias)<input type="number" min="1" max="3650" value={settings.premium_duration_days} onChange={e=>setSettings({...settings,premium_duration_days:Number(e.target.value)})} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/><span className="text-[10px] text-slate-500">O prazo do PRO começa quando o pagamento for confirmado e a assinatura for ativada.</span></label>
      <label className="grid gap-1 text-sm sm:col-span-2">Link de pagamento Premium<input value={settings.premium_payment_url||''} onChange={e=>setSettings({...settings,premium_payment_url:e.target.value||null})} placeholder="https://..." className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label>
    </div>
  </section>

  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5">
    <div className="mb-4 flex items-center gap-2"><Rocket size={20} className="text-geek-orange"/><div><h2 className="font-semibold">Configurações de Impulsionamento</h2><p className="text-xs text-slate-500">O impulsionamento é cobrado por dia. O usuário escolhe livremente entre 1 e 30 dias.</p></div></div>
    <div className="grid gap-4 sm:grid-cols-2">
      <label className="grid gap-1 text-sm">Preço por dia (R$)<input type="number" min="0" step="0.01" value={settings.boost_price_per_day} onChange={e=>setSettings({...settings,boost_price_per_day:Number(e.target.value)})} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/><span className="text-[10px] text-slate-500">Ex.: R$ 5,00/dia × 10 dias = R$ 50,00.</span></label>
      <div className="rounded-xl border border-geek-line bg-geek-soft p-3 text-sm"><b>Faixa permitida</b><p className="mt-1 text-xs text-slate-500">1 a 30 dias. Cada dia equivale a 24 horas de destaque após a ativação.</p></div>
      <label className="grid gap-1 text-sm sm:col-span-2">Link de pagamento Impulsionar<input value={settings.boost_payment_url||''} onChange={e=>setSettings({...settings,boost_payment_url:e.target.value||null})} placeholder="https://..." className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2.5"/></label>
    </div>
  </section>

  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5">
    <div className="mb-3 flex items-center gap-2"><Settings2 size={20} className="text-geek-orange"/><div><h2 className="font-semibold">Outras configurações</h2><p className="text-xs text-slate-500">Preferências gerais de monetização.</p></div></div>
    <label className="flex items-center gap-3 rounded-xl border border-geek-line bg-geek-soft p-3 text-sm"><input type="checkbox" checked={settings.pro_hides_ads} onChange={e=>setSettings({...settings,pro_hides_ads:e.target.checked})}/><span>Usuários PRO não recebem anúncios</span></label>
    <button onClick={saveSettings} disabled={saving} className="mt-4 flex items-center gap-2 rounded-xl bg-geek-orange px-4 py-3 font-semibold disabled:opacity-60"><Save size={17}/>{saving?'Salvando...':'Salvar configurações'}</button>
  </section>
 </div>}
 </div>
}
