'use client';

import { useEffect,useMemo,useRef,useState } from 'react';
import { CalendarDays, Image as ImageIcon, Loader2, Pencil, Plus, Trash2, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type EventRow={id:string;title:string;slug:string;description:string|null;category:string|null;cover_url:string|null;venue_name:string|null;address:string|null;city:string|null;state:string|null;is_online:boolean;external_url:string|null;starts_at:string;ends_at:string|null};

const empty={title:'',description:'',category:'',venue_name:'',address:'',city:'',state:'',is_online:false,external_url:'',starts_at:'',ends_at:'',cover_url:''};
const categories=['Anime','Games','HQs & Comics','Filmes','Séries','Cosplay','Mangá','K-Pop','RPG','Tecnologia','Colecionáveis','Convenção','Outro'];
const templates=[
 {name:'Convention',category:'Convenção',description:'Encontro de cultura pop e geek com atrações, experiências e comunidade.'},
 {name:'Torneio TCG',category:'Games',description:'Torneio de card game com partidas, comunidade e premiação.'},
 {name:'Mesa RPG',category:'RPG',description:'Sessão de RPG para reunir jogadores e viver uma nova aventura.'},
 {name:'Cosplay Contest',category:'Cosplay',description:'Concurso cosplay com apresentações e premiação.'},
 {name:'Watch Party',category:'Séries',description:'Encontro da comunidade para assistir e celebrar junto.'},
 {name:'K-Pop Meetup',category:'K-Pop',description:'Meetup K-Pop com comunidade, música e atividades temáticas.'}
];

function localInputValue(iso:string|null){if(!iso)return ''; const d=new Date(iso); const pad=(n:number)=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,70)}

export function AdminEventsClient(){
 const supabase=useMemo(()=>createClient(),[]); const inputRef=useRef<HTMLInputElement>(null);
 const [events,setEvents]=useState<EventRow[]>([]); const [form,setForm]=useState<any>(empty); const [editing,setEditing]=useState<string|null>(null); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 async function load(){setLoading(true);const {data}=await supabase.from('events').select('*').order('starts_at',{ascending:true});setEvents((data||[]) as EventRow[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 function chooseFile(next:File|null){setMessage('');if(!next){setFile(null);setPreview(null);return}if(!['image/jpeg','image/png','image/webp'].includes(next.type)){setMessage('A capa precisa ser JPG, PNG ou WEBP.');return}if(next.size>10*1024*1024){setMessage('A capa precisa ter no máximo 10 MB.');return}if(preview&&file)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next))}
 async function uploadCover(userId:string){if(!file)return form.cover_url||null;const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('events').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return supabase.storage.from('events').getPublicUrl(path).data.publicUrl}
 function reset(){if(preview&&file)URL.revokeObjectURL(preview);setEditing(null);setForm(empty);setFile(null);setPreview(null);if(inputRef.current)inputRef.current.value=''}
 function edit(e:EventRow){if(preview&&file)URL.revokeObjectURL(preview);setEditing(e.id);setForm({...e,starts_at:localInputValue(e.starts_at),ends_at:localInputValue(e.ends_at)});setFile(null);setPreview(e.cover_url);window.scrollTo({top:0,behavior:'smooth'})}
 function useTemplate(template:(typeof templates)[number]){setEditing(null);setMessage(`Modelo ${template.name} aplicado. Revise os dados antes de criar o evento.`);setForm({...empty,title:template.name,category:template.category,description:template.description});if(preview&&file)URL.revokeObjectURL(preview);setFile(null);setPreview(null);if(inputRef.current)inputRef.current.value=''}
 async function save(){setMessage('');if(!form.title.trim()||!form.starts_at){setMessage('Preencha pelo menos o nome e a data de início.');return}if(form.ends_at&&new Date(form.ends_at).getTime()<new Date(form.starts_at).getTime()){setMessage('A data de término não pode ser anterior ao início.');return}setSaving(true);const wasEditing=Boolean(editing);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada');const cover=await uploadCover(user.id);const payload={title:form.title.trim(),slug:slugify(form.title)+(editing?`-${editing.slice(0,8)}`:`-${Date.now().toString().slice(-6)}`),description:form.description.trim()||null,category:form.category||null,cover_url:cover,venue_name:form.venue_name.trim()||null,address:form.address.trim()||null,city:form.city.trim()||null,state:form.state.trim()||null,is_online:Boolean(form.is_online),external_url:form.external_url.trim()||null,starts_at:new Date(form.starts_at).toISOString(),ends_at:form.ends_at?new Date(form.ends_at).toISOString():null,created_by:user.id,updated_at:new Date().toISOString()};let error:any;if(editing){({error}=await supabase.from('events').update(payload).eq('id',editing))}else{({error}=await supabase.from('events').insert(payload))}if(error)throw error;reset();setMessage(wasEditing?'Evento atualizado.':'Evento criado.');await load()}catch{setMessage('Não foi possível salvar o evento. Confira os dados e tente novamente.')}setSaving(false)}
 async function remove(id:string){if(!window.confirm('Excluir este evento? Essa ação não pode ser desfeita.'))return;await supabase.from('events').delete().eq('id',id);if(editing===id)reset();await load()}
 return <div className="mx-auto max-w-7xl space-y-6">
  <div><p className="text-sm font-bold text-geek-orange">ADMINISTRAÇÃO</p><h1 className="text-2xl sm:text-3xl font-black">Eventos</h1><p className="mt-2 text-sm text-slate-400">Somente administradores podem criar, editar e remover eventos oficiais.</p></div>
  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-6"><div className="mb-4 flex items-center gap-2"><CalendarDays className="text-geek-orange"/><h2 className="text-lg font-black">{editing?'Editar evento':'Novo evento'}</h2>{editing&&<button onClick={reset} className="ml-auto rounded-lg border border-geek-line p-2" aria-label="Cancelar edição"><X size={16}/></button>}</div>
   {!editing&&<div className="mb-5"><p className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-slate-500">Modelos rápidos</p><div className="flex flex-wrap gap-2">{templates.map(template=><button key={template.name} onClick={()=>useTemplate(template)} className="rounded-full border border-geek-line bg-geek-soft px-3 py-2 text-xs font-semibold text-slate-300 transition hover:border-orange-500/40 hover:text-orange-300">{template.name}</button>)}</div></div>}
   <div className="grid gap-3 md:grid-cols-2"><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Nome do evento" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><select value={form.category} onChange={e=>set('category',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Categoria</option>{categories.map(c=><option key={c}>{c}</option>)}</select><input type="datetime-local" value={form.starts_at} onChange={e=>set('starts_at',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input type="datetime-local" value={form.ends_at} onChange={e=>set('ends_at',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.venue_name} onChange={e=>set('venue_name',e.target.value)} placeholder="Nome do local" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.address} onChange={e=>set('address',e.target.value)} placeholder="Endereço" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.city} onChange={e=>set('city',e.target.value)} placeholder="Cidade" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.state} onChange={e=>set('state',e.target.value)} placeholder="Estado/UF" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.external_url} onChange={e=>set('external_url',e.target.value)} placeholder="Link externo (opcional)" className="rounded-xl border border-geek-line bg-geek-soft p-3 md:col-span-2"/><textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Descrição" className="min-h-28 rounded-xl border border-geek-line bg-geek-soft p-3 md:col-span-2"/></div>
   <label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_online} onChange={e=>set('is_online',e.target.checked)}/> Evento online</label>
   <input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>chooseFile(e.target.files?.[0]||null)}/><div className="mt-4 flex flex-wrap items-center gap-3"><button onClick={()=>inputRef.current?.click()} className="rounded-xl border border-geek-line px-3 py-2 text-sm flex items-center gap-2"><ImageIcon size={17}/>Selecionar capa</button><span className="text-xs text-slate-500">JPG, PNG ou WEBP · até 10 MB · exibida centralizada e sem deformar</span></div>{preview&&<div className="mt-3 aspect-[16/7] max-w-2xl overflow-hidden rounded-xl border border-geek-line bg-black/20"><img src={preview} alt="Prévia da capa" className="h-full w-full object-contain object-center"/></div>}
   {message&&<p className="mt-3 text-sm text-slate-300">{message}</p>}<button onClick={save} disabled={saving} className="mt-4 rounded-xl bg-geek-orange px-5 py-3 font-bold disabled:opacity-50 flex items-center gap-2">{saving?<Loader2 size={18} className="animate-spin"/>:<Plus size={18}/>} {editing?'Salvar alterações':'Criar evento'}</button>
  </section>
  <section><h2 className="mb-3 text-lg font-black">Eventos cadastrados</h2>{loading?<div className="py-10 grid place-items-center"><Loader2 className="animate-spin"/></div>:events.length===0?<div className="rounded-2xl border border-dashed border-geek-line bg-geek-panel p-8 text-center text-slate-400">Nenhum evento cadastrado.</div>:<div className="grid gap-3">{events.map(e=><article key={e.id} className="rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><b>{e.title}</b><p className="text-xs text-slate-400">{e.category||'Sem categoria'} · {new Date(e.starts_at).toLocaleString('pt-BR')} · {[e.city,e.state].filter(Boolean).join('/')||'Local não informado'}</p></div><div className="flex gap-2"><button onClick={()=>edit(e)} className="rounded-xl border border-geek-line px-3 py-2 text-sm flex items-center gap-2"><Pencil size={15}/>Editar</button><button onClick={()=>remove(e.id)} className="rounded-xl border border-red-500/30 px-3 py-2 text-sm text-red-300 flex items-center gap-2"><Trash2 size={15}/>Excluir</button></div></div></article>)}</div>}</section>
 </div>;
}
