'use client';

import { useEffect,useMemo,useState } from 'react';
import { Rocket, Sparkles } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Benefits={is_pro:boolean;is_ambassador:boolean;credits_allowance:number;credits_used:number;credits_remaining:number};
type Post={id:string;content:string|null;created_at:string;is_boosted:boolean;boosted_until:string|null};

export function BoostCreditPanel(){
 const supabase=useMemo(()=>createClient(),[]);const [benefits,setBenefits]=useState<Benefits|null>(null);const [posts,setPosts]=useState<Post[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState<string|null>(null);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:b},{data:p}]=await Promise.all([supabase.rpc('get_my_benefits'),supabase.from('posts').select('id,content,created_at,is_boosted,boosted_until').eq('author_id',user.id).order('created_at',{ascending:false}).limit(20)]);setBenefits(((b||[]) as Benefits[])[0]||null);setPosts((p||[]) as Post[])}
 useEffect(()=>{void load()},[supabase]);
 if(!benefits||benefits.credits_allowance<=0)return null;
 async function use(postId:string,credits:number){setBusy(postId);setMessage('');const {data,error}=await supabase.rpc('use_boost_credits',{target_post:postId,credits});if(error)setMessage(error.message.includes('insuficientes')?'Você não possui créditos suficientes para esse pacote.':'Não foi possível usar os créditos agora.');else{const row=((data||[]) as {active_until:string;credits_remaining:number}[])[0];setMessage(`Impulsionamento ativado com crédito Premium${row?.active_until?` até ${new Date(row.active_until).toLocaleString('pt-BR')}`:''}.`);await load()}setBusy(null)}
 return <section className="mb-5 rounded-2xl border border-orange-500/30 bg-orange-500/5 p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-orange-500/15 text-orange-300"><Sparkles size={19}/></div><div><h2 className="font-black">Créditos {benefits.is_ambassador?'de Embaixador':'Premium'}</h2><p className="text-sm text-slate-400">Você tem <b className="text-orange-200">{benefits.credits_remaining} de {benefits.credits_allowance}</b> créditos disponíveis neste mês. Depois que acabarem, o impulsionamento pago continua disponível normalmente.</p></div></div>{message&&<div className="mt-3 rounded-xl border border-geek-line bg-geek-panel px-3 py-2 text-sm text-slate-300">{message}</div>}<div className="mt-4 grid gap-2">{posts.slice(0,6).map(post=><div key={post.id} className="rounded-xl border border-geek-line bg-geek-panel p-3"><p className="line-clamp-1 text-sm font-semibold">{post.content||'Publicação sem texto'}</p><p className="mt-1 text-[10px] text-slate-500">{new Date(post.created_at).toLocaleString('pt-BR')}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void use(post.id,1)} disabled={busy===post.id||benefits.credits_remaining<1} className="rounded-lg bg-geek-orange px-3 py-2 text-xs font-black disabled:opacity-40"><Rocket size={13} className="mr-1 inline"/>1 crédito · 1 dia</button><button onClick={()=>void use(post.id,2)} disabled={busy===post.id||benefits.credits_remaining<2} className="rounded-lg border border-orange-500/30 px-3 py-2 text-xs font-black text-orange-200 disabled:opacity-40">2 créditos · 3 dias</button>{benefits.is_ambassador&&<button onClick={()=>void use(post.id,3)} disabled={busy===post.id||benefits.credits_remaining<3} className="rounded-lg border border-violet-500/30 px-3 py-2 text-xs font-black text-violet-200 disabled:opacity-40">3 créditos · 7 dias</button>}</div></div>)}</div></section>;
}
