'use client';

import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { Camera, Plus,Trash2,Loader2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { ImageCropper } from '@/components/image-cropper';
import { PhotoSourcePicker } from '@/components/photo-source-picker';

type Item={id:string;owner_id:string;title:string;image_url:string|null;category:string|null;item_type:string|null;status:string;notes:string|null;created_at:string};

const statuses=['Tenho','Quero','Troca'];
const types=['Figure','Mangá','Card','Game','HQ','Colecionável','Outro'];

export function CollectionClient(){
 const supabase=useMemo(()=>createClient(),[]);
 const [userId,setUserId]=useState<string|null>(null);
 const [items,setItems]=useState<Item[]>([]);
 const [loading,setLoading]=useState(true);
 const [creating,setCreating]=useState(false);
 const [title,setTitle]=useState(''); const [category,setCategory]=useState('Games'); const [type,setType]=useState('Figure'); const [status,setStatus]=useState('Tenho'); const [notes,setNotes]=useState('');
 const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [cropSource,setCropSource]=useState<File|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');

 async function load(){const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);if(!user){setLoading(false);return;}const {data}=await supabase.from('collection_items').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});setItems((data||[]) as Item[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);

 function choose(f:File|null){setMessage('');if(!f){setCropSource(null);return;}if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setMessage('Envie uma imagem JPG, PNG ou WEBP.');return;}if(f.size>10*1024*1024){setMessage('A imagem deve ter no máximo 10 MB.');return;}setCropSource(f)}
 function clearPhoto(){if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview(null);setCropSource(null)}
 function confirmCrop(cropped:File,previewUrl:string){if(preview)URL.revokeObjectURL(preview);setFile(cropped);setPreview(previewUrl);setCropSource(null)}

 async function save(){if(!userId||!title.trim())return;setSaving(true);setMessage('');try{let imageUrl:string|null=null;if(file){const path=`${userId}/${crypto.randomUUID()}.webp`;const {error}=await supabase.storage.from('collection').upload(path,file,{contentType:'image/webp',cacheControl:'3600'});if(error)throw error;imageUrl=supabase.storage.from('collection').getPublicUrl(path).data.publicUrl;}const {error}=await supabase.from('collection_items').insert({owner_id:userId,title:title.trim(),image_url:imageUrl,category,item_type:type,status,notes:notes.trim()||null});if(error)throw error;setTitle('');setNotes('');clearPhoto();setCreating(false);await load();}catch{setMessage('Não foi possível adicionar o item. Tente novamente.')}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm('Remover este item da sua coleção?'))return;await supabase.from('collection_items').delete().eq('id',id);await load()}
 async function changeStatus(id:string,value:string){await supabase.from('collection_items').update({status:value}).eq('id',id);setItems(current=>current.map(i=>i.id===id?{...i,status:value}:i))}

 const counts=statuses.reduce((acc,s)=>({...acc,[s]:items.filter(i=>i.status===s).length}),{} as Record<string,number>);
 if(loading)return <div className="py-20 grid place-items-center"><Loader2 className="animate-spin text-geek-orange"/></div>;

 return <div className="mx-auto max-w-6xl px-3 sm:px-4 space-y-5">{cropSource&&<ImageCropper file={cropSource} aspect={1} title="Ajustar foto do item" outputWidth={1200} onCancel={()=>setCropSource(null)} onConfirm={confirmCrop}/>}<div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl sm:text-3xl font-black">Minha Coleção</h1><p className="mt-1 text-sm text-slate-400">Sua estante digital geek.</p></div><button onClick={()=>setCreating(v=>!v)} className="rounded-xl bg-geek-orange px-4 py-2.5 text-sm font-bold inline-flex items-center justify-center gap-2"><Plus size={17}/>{creating?'Fechar':'Adicionar item'}</button></div>
 <div className="grid grid-cols-3 gap-3">{statuses.map(s=><div key={s} className="rounded-2xl border border-geek-line bg-geek-panel p-4 text-center"><b className="text-xl">{counts[s]||0}</b><p className="text-xs text-slate-500">{s}</p></div>)}</div>
 {creating&&<section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="grid gap-4 lg:grid-cols-[220px,1fr]"><div><PhotoSourcePicker onSelect={choose} label={preview?'Trocar foto':'Carregar ou tirar uma foto'} className="aspect-square w-full overflow-hidden rounded-2xl border border-dashed border-geek-line bg-black/20 flex items-center justify-center" cameraFacing="environment"/>{preview?<div className="pointer-events-none -mt-[100%] aspect-square w-full overflow-hidden rounded-2xl"><img src={preview} alt="Prévia" className="h-full w-full object-cover object-center"/></div>:<div className="pointer-events-none -mt-[100%] aspect-square w-full flex items-center justify-center"><span className="flex flex-col items-center gap-2 text-sm text-slate-400"><Camera size={24}/>Carregar ou tirar uma foto</span></div>}{preview&&<button onClick={clearPhoto} className="mt-2 w-full rounded-xl border border-geek-line px-3 py-2 text-xs text-slate-400">Remover foto</button>}<p className="mt-2 text-xs leading-5 text-slate-500">Ao selecionar, você poderá dar zoom, reposicionar e confirmar o recorte sem deformar a imagem.</p></div><div className="grid gap-3 sm:grid-cols-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nome do item" className="sm:col-span-2 rounded-xl border border-geek-line bg-geek-soft px-3 py-3 outline-none"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Categoria" className="rounded-xl border border-geek-line bg-geek-soft px-3 py-3 outline-none"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-3">{types.map(t=><option key={t}>{t}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-3">{statuses.map(s=><option key={s}>{s}</option>)}</select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações (opcional)" className="rounded-xl border border-geek-line bg-geek-soft px-3 py-3 outline-none"/><button onClick={save} disabled={saving||!title.trim()} className="sm:col-span-2 rounded-xl bg-geek-orange py-3 font-bold disabled:opacity-50">{saving?'Salvando...':'Salvar item'}</button>{message&&<p className="sm:col-span-2 text-xs text-red-400">{message}</p>}</div></div></section>}
 {items.length===0?<div className="rounded-2xl border border-dashed border-geek-line bg-geek-panel p-12 text-center text-slate-400">Sua coleção ainda está vazia.</div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel"><Link href={`/colecao/${item.id}`} className="block"><div className="aspect-square bg-black/20 flex items-center justify-center overflow-hidden">{item.image_url?<img src={item.image_url} alt={item.title} className="h-full w-full object-contain object-center"/>:<span className="flex flex-col items-center gap-2 text-xs text-slate-500"><Camera size={18}/>Sem foto</span>}</div></Link><div className="p-4"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><Link href={`/colecao/${item.id}`} className="block truncate font-bold hover:text-orange-300">{item.title}</Link><p className="text-xs text-slate-500">{[item.item_type,item.category].filter(Boolean).join(' · ')}</p></div><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-red-300 hover:bg-red-500/10"><Trash2 size={16}/></button></div><Link href={`/colecao/${item.id}`} className="mt-3 block rounded-xl border border-geek-line px-3 py-2 text-center text-xs font-bold hover:bg-geek-soft">Ver detalhes</Link><select value={item.status} onChange={e=>changeStatus(item.id,e.target.value)} className="mt-2 w-full rounded-xl border border-geek-line bg-geek-soft px-3 py-2 text-sm">{statuses.map(s=><option key={s}>{s}</option>)}</select>{item.notes&&<p className="mt-2 text-xs text-slate-400 line-clamp-2">{item.notes}</p>}</div></article>)}</div>}
 </div>;
}