'use client';

import { useEffect,useMemo,useState } from 'react';
import { Loader2, Plus, Search, Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Community={id:string;owner_id:string;name:string;slug:string;description:string|null;category:string|null;cover_url:string|null;visibility:string;created_at:string};

export function CommunitiesClient(){
 const supabase=useMemo(()=>createClient(),[]); const [rows,setRows]=useState<Community[]>([]); const [members,setMembers]=useState<Record<string,number>>({}); const [mine,setMine]=useState<Set<string>>(new Set()); const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'explorar'|'minhas'>('explorar'); const [search,setSearch]=useState(''); const [showCreate,setShowCreate]=useState(false); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState('Games'); const [visibility,setVisibility]=useState('public'); const [message,setMessage]=useState('');
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);const {data}=await supabase.from('communities').select('*').order('created_at',{ascending:false});const safe=(data||[]) as Community[];setRows(safe);const ids=safe.map(x=>x.id);if(ids.length){const {data:m}=await supabase.from('community_members').select('community_id,user_id').in('community_id',ids);const counts:Record<string,number>={};const me=new Set<string>();(m||[]).forEach((x:any)=>{counts[x.community_id]=(counts[x.community_id]||0)+1;if(user&&x.user_id===user.id)me.add(x.community_id)});setMembers(counts);setMine(me)}setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function join(id:string){if(!userId)return;if(mine.has(id))await supabase.from('community_members').delete().eq('community_id',id).eq('user_id',userId);else await supabase.from('community_members').insert({community_id:id,user_id:userId,member_role:'member'});await load()}
 async function create(){if(!userId||name.trim().length<3)return;setMessage('');const slug=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5);const {data,error}=await supabase.from('communities').insert({owner_id:userId,name:name.trim(),slug,description:description.trim()||null,category,visibility}).select('id').single();if(error){setMessage('Não foi possível criar a comunidade.');return}if(data?.id)await supabase.from('community_members').insert({community_id:data.id,user_id:userId,member_role:'owner'});setName('');setDescription('');setShowCreate(false);await load()}
 const visible=rows.filter(r=>{if(tab==='minhas'&&!mine.has(r.id)&&r.owner_id!==userId)return false;const q=search.toLowerCase().trim();return !q||r.name.toLowerCase().includes(q)||(r.description||'').toLowerCase().includes(q)||(r.category||'').toLowerCase().includes(q)});
 return <div className="mx-auto max-w-5xl px-3 sm:px-4"><div className="mb-5 flex flex-wrap items-end gap-3"><div><h1 className="text-2xl font-black">Comunidades</h1><p className="mt-1 text-sm text-slate-400">Encontre fandoms e pessoas com os mesmos interesses.</p></div><button onClick={()=>setShowCreate(v=>!v)} className="ml-auto rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold flex items-center gap-2"><Plus size={17}/>Criar comunidade</button></div>
 {showCreate&&<section className="mb-4 rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="grid gap-3 sm:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da comunidade" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3">{['Games','Anime','HQs & Comics','Filmes','Séries','Cosplay','Mangá','K-Pop','RPG','Tecnologia','Colecionáveis'].map(c=><option key={c}>{c}</option>)}</select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição" className="min-h-24 rounded-xl border border-geek-line bg-geek-soft p-3 sm:col-span-2"/><select value={visibility} onChange={e=>setVisibility(e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="public">Aberta</option><option value="private">Fechada</option></select><button onClick={create} className="rounded-xl bg-geek-orange px-4 py-3 font-bold">Criar</button></div>{message&&<p className="mt-2 text-sm text-red-400">{message}</p>}</section>}
 <div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="flex rounded-xl border border-geek-line bg-geek-panel p-1"><button onClick={()=>setTab('explorar')} className={`rounded-lg px-4 py-2 text-sm ${tab==='explorar'?'bg-geek-orange text-white':'text-slate-400'}`}>Explorar</button><button onClick={()=>setTab('minhas')} className={`rounded-lg px-4 py-2 text-sm ${tab==='minhas'?'bg-geek-orange text-white':'text-slate-400'}`}>Minhas</button></div><div className="flex flex-1 items-center gap-2 rounded-xl border border-geek-line bg-geek-panel px-3"><Search size={16} className="text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar comunidades" className="w-full bg-transparent py-2 outline-none"/></div></div>
 {loading?<div className="py-20 grid place-items-center"><Loader2 className="animate-spin text-geek-orange"/></div>:visible.length===0?<div className="rounded-2xl border border-dashed border-geek-line bg-geek-panel p-10 text-center text-slate-400"><Users className="mx-auto mb-3 text-geek-orange"/>Nenhuma comunidade encontrada.</div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(c=><article key={c.id} className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel"><div className="h-24 bg-gradient-to-br from-orange-500/30 via-purple-500/20 to-cyan-500/10">{c.cover_url&&<img src={c.cover_url} alt="" className="h-full w-full object-cover"/>}</div><div className="p-4"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h2 className="font-black">{c.name}</h2><p className="text-xs text-slate-500">{c.category||'Geek'} · {c.visibility==='public'?'Aberta':'Fechada'}</p></div><span className="text-xs text-slate-400 flex items-center gap-1"><Users size={14}/>{members[c.id]||0}</span></div>{c.description&&<p className="mt-3 text-sm text-slate-400 line-clamp-3">{c.description}</p>}<button onClick={()=>join(c.id)} disabled={c.owner_id===userId} className={`mt-4 w-full rounded-xl px-3 py-2 text-sm font-bold ${mine.has(c.id)||c.owner_id===userId?'border border-geek-line text-slate-300':'bg-geek-orange text-white'}`}>{c.owner_id===userId?'Você é o dono':mine.has(c.id)?'Sair da comunidade':'Entrar na comunidade'}</button></div></article>)}</div>}
 </div>;
}
