'use client';

import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

const interestOptions=['Anime','Games','HQs & Comics','Filmes','Séries','Cosplay','Mangá','K-Pop','RPG','Tecnologia','Colecionáveis'];
const areaOptions=['Palco','Artistas','Lojas','Alimentação','Games','RPG','Cosplay','K-Pop','Outros'];
const spendOptions=['Alimentação','Lojas','Artistas','Games','Ingressos/atividades','Outros'];

export function EventFeedbackClient({eventId}:{eventId:string}){
 const supabase=useMemo(()=>createClient(),[]); const router=useRouter(); const [step,setStep]=useState(0); const [sending,setSending]=useState(false); const [error,setError]=useState('');
 const [form,setForm]=useState<any>({age_range:'',city:'',occupation:'',income_range:'',interests:[],main_interest:'',monthly_geek_spend:'',first_time:null,discovery_channel:'',reason:'',came_with:'',time_at_event:'',areas_visited:[],longest_area:'',event_spend:'',spend_categories:[],from_other_city:null,nights:0,score:null,would_return:null,improvement:''});
 const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const toggle=(key:string,value:string)=>setForm((f:any)=>({...f,[key]:f[key].includes(value)?f[key].filter((x:string)=>x!==value):[...f[key],value]}));
 const steps=['Perfil','Interesses','Relação com o evento','Comportamento','Consumo','Turismo','Satisfação'];
 async function submit(){setSending(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Sua sessão expirou. Entre novamente.');setSending(false);return;}const {data:attendee}=await supabase.from('event_attendees').select('event_id').eq('event_id',eventId).eq('user_id',user.id).eq('status','going').maybeSingle();if(!attendee){setError('Esta avaliação só está disponível para quem confirmou presença no evento.');setSending(false);return;}const {error:e}=await supabase.from('event_feedback').insert({...form,event_id:eventId,user_id:user.id});if(e){setError(e.code==='23505'?'Você já enviou uma avaliação para este evento.':'Não foi possível enviar sua avaliação.');setSending(false);return;}router.push('/eventos');router.refresh();}
 const chip=(label:string,key:string)=><button type="button" onClick={()=>toggle(key,label)} className={`rounded-full border px-3 py-2 text-sm ${form[key].includes(label)?'border-geek-orange bg-geek-orange text-white':'border-geek-line bg-geek-soft text-slate-300'}`}>{label}</button>;
 return <div className="mx-auto max-w-3xl px-3 sm:px-4"><div className="mb-5"><p className="text-sm font-bold text-geek-orange">PESQUISA PÓS-EVENTO</p><h1 className="text-2xl font-black">Conte como foi sua experiência</h1><p className="mt-1 text-sm text-slate-400">Suas respostas ajudam a melhorar eventos e gerar inteligência para a comunidade geek.</p></div>
 <div className="mb-4 flex gap-1">{steps.map((s,i)=><div key={s} className={`h-2 flex-1 rounded-full ${i<=step?'bg-geek-orange':'bg-geek-soft'}`}/>)}</div>
 <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-6"><div className="mb-5"><span className="text-xs text-slate-500">Etapa {step+1} de {steps.length}</span><h2 className="text-xl font-black">{steps[step]}</h2></div>
 {step===0&&<div className="grid gap-3 sm:grid-cols-2"><select value={form.age_range} onChange={e=>set('age_range',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Faixa etária</option><option>Até 17</option><option>18 a 24</option><option>25 a 34</option><option>35 a 44</option><option>45 ou mais</option></select><input value={form.city} onChange={e=>set('city',e.target.value)} placeholder="Cidade" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.occupation} onChange={e=>set('occupation',e.target.value)} placeholder="Ocupação" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><select value={form.income_range} onChange={e=>set('income_range',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Faixa de renda</option><option>Até 1 salário mínimo</option><option>1 a 3 salários mínimos</option><option>3 a 5 salários mínimos</option><option>5 a 10 salários mínimos</option><option>Acima de 10 salários mínimos</option><option>Prefiro não informar</option></select></div>}
 {step===1&&<div className="space-y-4"><div><p className="mb-2 text-sm font-bold">Quais universos mais interessam você?</p><div className="flex flex-wrap gap-2">{interestOptions.map(x=>chip(x,'interests'))}</div></div><select value={form.main_interest} onChange={e=>set('main_interest',e.target.value)} className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Seu principal interesse</option>{interestOptions.map(x=><option key={x}>{x}</option>)}</select><select value={form.monthly_geek_spend} onChange={e=>set('monthly_geek_spend',e.target.value)} className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Quanto gasta por mês com cultura geek?</option><option>Até R$ 100</option><option>R$ 101 a R$ 300</option><option>R$ 301 a R$ 600</option><option>R$ 601 a R$ 1.000</option><option>Mais de R$ 1.000</option></select></div>}
 {step===2&&<div className="grid gap-3"><select value={form.first_time===null?'':String(form.first_time)} onChange={e=>set('first_time',e.target.value==='true')} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Foi sua primeira vez neste evento?</option><option value="true">Sim</option><option value="false">Não</option></select><input value={form.discovery_channel} onChange={e=>set('discovery_channel',e.target.value)} placeholder="Como ficou sabendo do evento?" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.reason} onChange={e=>set('reason',e.target.value)} placeholder="Principal motivo para participar" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.came_with} onChange={e=>set('came_with',e.target.value)} placeholder="Você veio sozinho, com amigos, família...?" className="rounded-xl border border-geek-line bg-geek-soft p-3"/></div>}
 {step===3&&<div className="space-y-4"><input value={form.time_at_event} onChange={e=>set('time_at_event',e.target.value)} placeholder="Quanto tempo permaneceu no evento?" className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"/><div><p className="mb-2 text-sm font-bold">Quais áreas visitou?</p><div className="flex flex-wrap gap-2">{areaOptions.map(x=>chip(x,'areas_visited'))}</div></div><input value={form.longest_area} onChange={e=>set('longest_area',e.target.value)} placeholder="Onde passou mais tempo?" className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"/></div>}
 {step===4&&<div className="space-y-4"><select value={form.event_spend} onChange={e=>set('event_spend',e.target.value)} className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Quanto gastou no evento?</option><option>Não gastei</option><option>Até R$ 50</option><option>R$ 51 a R$ 150</option><option>R$ 151 a R$ 300</option><option>R$ 301 a R$ 600</option><option>Mais de R$ 600</option></select><div><p className="mb-2 text-sm font-bold">Onde gastou?</p><div className="flex flex-wrap gap-2">{spendOptions.map(x=>chip(x,'spend_categories'))}</div></div></div>}
 {step===5&&<div className="grid gap-3"><select value={form.from_other_city===null?'':String(form.from_other_city)} onChange={e=>set('from_other_city',e.target.value==='true')} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Veio de outra cidade?</option><option value="true">Sim</option><option value="false">Não</option></select>{form.from_other_city===true&&<input type="number" min={0} max={30} value={form.nights} onChange={e=>set('nights',Number(e.target.value))} placeholder="Quantas noites ficou hospedado?" className="rounded-xl border border-geek-line bg-geek-soft p-3"/>}</div>}
 {step===6&&<div className="space-y-4"><div><p className="mb-2 text-sm font-bold">De 0 a 10, que nota você dá ao evento?</p><div className="grid grid-cols-6 gap-2 sm:grid-cols-11">{Array.from({length:11},(_,i)=>i).map(i=><button type="button" key={i} onClick={()=>set('score',i)} className={`rounded-xl border p-2 text-sm ${form.score===i?'border-geek-orange bg-geek-orange text-white':'border-geek-line bg-geek-soft'}`}>{i}</button>)}</div></div><select value={form.would_return===null?'':String(form.would_return)} onChange={e=>set('would_return',e.target.value==='true')} className="w-full rounded-xl border border-geek-line bg-geek-soft p-3"><option value="">Voltaria em uma próxima edição?</option><option value="true">Sim</option><option value="false">Não</option></select><textarea value={form.improvement} onChange={e=>set('improvement',e.target.value)} placeholder="O que poderia melhorar?" className="min-h-28 w-full rounded-xl border border-geek-line bg-geek-soft p-3"/></div>}
 {error&&<p className="mt-4 text-sm text-red-400">{error}</p>}
 <div className="mt-6 flex gap-2"><button type="button" disabled={step===0||sending} onClick={()=>setStep(s=>Math.max(0,s-1))} className="rounded-xl border border-geek-line px-4 py-2 text-sm disabled:opacity-40 flex items-center gap-2"><ArrowLeft size={16}/>Voltar</button>{step<steps.length-1?<button type="button" onClick={()=>setStep(s=>Math.min(steps.length-1,s+1))} className="ml-auto rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold flex items-center gap-2">Continuar<ArrowRight size={16}/></button>:<button type="button" disabled={sending} onClick={submit} className="ml-auto rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold flex items-center gap-2 disabled:opacity-50"><CheckCircle2 size={17}/>{sending?'Enviando...':'Enviar avaliação'}</button>}</div>
 </section></div>;
}
