'use client';

import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { Check, Flame, Loader2, Medal, Target, Trophy } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Daily={posts_count:number;comments_count:number;likes_count:number;events_count:number;claimed_missions:string[]};
type Ranked={user_id:string;display_name:string;username:string|null;avatar_url:string|null;level:number;weekly_score:number};
type Mission={key:string;label:string;description:string;reward:number;current:number;target:number};

export function GamificationDashboard(){
 const supabase=useMemo(()=>createClient(),[]);const [loading,setLoading]=useState(true);const [streak,setStreak]=useState(0);const [daily,setDaily]=useState<Daily>({posts_count:0,comments_count:0,likes_count:0,events_count:0,claimed_missions:[]});const [ranking,setRanking]=useState<Ranked[]>([]);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const [{data:streakData},{data:activity},{data:rankRows}]=await Promise.all([supabase.rpc('register_daily_login'),supabase.from('user_daily_activity').select('posts_count,comments_count,likes_count,events_count,claimed_missions').eq('user_id',user.id).eq('activity_date',new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})).maybeSingle(),supabase.rpc('weekly_geek_ranking')]);setStreak(Number(streakData||0));if(activity)setDaily(activity as Daily);setRanking(((rankRows||[]) as Ranked[]).map(r=>({...r,weekly_score:Number(r.weekly_score||0)})));setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 const missions:Mission[]=[{key:'post_1',label:'Primeira publicação do dia',description:'Publique 1 vez hoje.',reward:10,current:daily.posts_count,target:1},{key:'comments_3',label:'Entrar na conversa',description:'Comente em 3 publicações hoje.',reward:15,current:daily.comments_count,target:3},{key:'likes_5',label:'Espalhar energia geek',description:'Curta 5 publicações hoje.',reward:10,current:daily.likes_count,target:5},{key:'event_1',label:'Agenda geek',description:'Confirme presença em 1 evento hoje.',reward:20,current:daily.events_count,target:1}];
 async function claim(mission:Mission){if(mission.current<mission.target||daily.claimed_missions.includes(mission.key))return;setBusy(mission.key);setMessage('');const {data,error}=await supabase.rpc('claim_daily_mission',{mission_key:mission.key});setBusy(null);if(error){setMessage(error.message.includes('JÁ')?'Esta missão já foi resgatada.':'Não foi possível resgatar esta missão.');return}setMessage(`Missão concluída: +${Number(data||mission.reward)} XP!`);await load()}
 if(loading)return <div className="grid place-items-center py-12"><Loader2 className="animate-spin text-geek-orange"/></div>;
 return <section className="mx-auto mt-6 w-full max-w-5xl space-y-5 px-3 pb-6 sm:px-4">
  <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-orange-500/30 bg-gradient-to-br from-orange-500/12 to-geek-panel p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-orange-500/15 text-orange-300"><Flame size={24}/></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Sequência de acesso</p><p className="text-2xl font-black">{streak} dia{streak===1?'':'s'} seguido{streak===1?'':'s'}</p></div></div><p className="mt-3 text-xs leading-5 text-slate-500">Abra o GeekoPlay em dias consecutivos para manter sua sequência.</p></div><div className="rounded-2xl border border-geek-line bg-geek-panel p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-xl bg-yellow-500/10 text-yellow-300"><Medal size={24}/></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Ranking semanal</p><p className="text-2xl font-black">Top Geeks</p></div></div><p className="mt-3 text-xs leading-5 text-slate-500">Pontuação dos últimos 7 dias com posts, comentários, curtidas e eventos.</p></div></div>
  {message&&<div className="rounded-xl border border-geek-line bg-geek-panel px-4 py-3 text-sm text-slate-300">{message}</div>}
  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><Target size={19} className="text-geek-orange"/><div><h2 className="font-black">Missões diárias</h2><p className="text-xs text-slate-500">Complete e resgate XP extra. As missões reiniciam a cada dia.</p></div></div><div className="grid gap-3 md:grid-cols-2">{missions.map(m=>{const done=m.current>=m.target;const claimed=daily.claimed_missions.includes(m.key);const percent=Math.min(100,(m.current/m.target)*100);return <article key={m.key} className="rounded-xl border border-geek-line bg-geek-soft p-4"><div className="flex items-start gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${claimed?'bg-green-500/10 text-green-300':'bg-orange-500/10 text-orange-300'}`}>{claimed?<Check size={18}/>:<Target size={18}/>}</div><div className="min-w-0 flex-1"><b className="text-sm">{m.label}</b><p className="mt-1 text-xs text-slate-500">{m.description} · +{m.reward} XP</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/20"><div className={`h-full rounded-full ${claimed?'bg-green-500':'bg-geek-orange'}`} style={{width:`${percent}%`}}/></div><div className="mt-2 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{Math.min(m.current,m.target)}/{m.target}</span><button onClick={()=>void claim(m)} disabled={!done||claimed||busy===m.key} className="rounded-lg border border-orange-500/25 bg-orange-500/10 px-3 py-1.5 text-xs font-bold text-orange-200 disabled:cursor-default disabled:border-geek-line disabled:bg-transparent disabled:text-slate-600">{busy===m.key?'Resgatando...':claimed?'Resgatada':done?'Resgatar XP':'Em andamento'}</button></div></article>})}</div></section>
  <section className="rounded-2xl border border-geek-line bg-geek-panel p-4 sm:p-5"><div className="mb-4 flex items-center gap-2"><Trophy size={19} className="text-yellow-400"/><div><h2 className="font-black">Top Geeks da semana</h2><p className="text-xs text-slate-500">Ranking de atividade dos últimos 7 dias.</p></div></div>{ranking.length===0?<p className="py-8 text-center text-sm text-slate-500">O ranking começa a aparecer conforme a comunidade participa.</p>:<div className="space-y-2">{ranking.slice(0,10).map((person,index)=><Link key={person.user_id} href={`/perfil/${person.user_id}`} className="flex items-center gap-3 rounded-xl border border-geek-line bg-geek-soft p-3 transition hover:border-orange-500/30"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg text-sm font-black ${index===0?'bg-yellow-500/15 text-yellow-300':index===1?'bg-slate-300/10 text-slate-300':index===2?'bg-orange-700/15 text-orange-300':'text-slate-500'}`}>{index+1}º</span><div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-orange-400 to-purple-600">{person.avatar_url?<img src={person.avatar_url} alt="" className="h-full w-full object-cover object-center"/>:<span className="font-black">{person.display_name.slice(0,1).toUpperCase()}</span>}</div><div className="min-w-0 flex-1"><b className="block truncate text-sm">{person.display_name}</b><p className="truncate text-xs text-slate-500">@{person.username||'geek'} · Nível {person.level}</p></div><b className="shrink-0 text-sm text-orange-300">{person.weekly_score} pts</b></Link>)}</div>}</section>
 </section>;
}
