'use client';

import { useEffect,useMemo,useRef,useState } from 'react';
import { Image as ImageIcon, Loader2, Plus, Search, Store, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Item={id:string;seller_id:string;title:string;description:string|null;image_urls:string[];price:number;category:string|null;item_condition:string|null;city:string|null;state:string|null;whatsapp:string|null;instagram:string|null;status:string;created_at:string};
const categories=['Games','Anime','HQs & Comics','Filmes','Séries','Cosplay','Mangá','K-Pop','RPG','Tecnologia','Colecionáveis','Outros'];

export function MarketClient(){
 const supabase=useMemo(()=>createClient(),[]); const fileRef=useRef<HTMLInputElement>(null); const [rows,setRows]=useState<Item[]>([]); const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [categoryFilter,setCategoryFilter]=useState('Todos'); const [showForm,setShowForm]=useState(false); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [message,setMessage]=useState(''); const [form,setForm]=useState<any>({title:'',description:'',price:'',category:'Colecionáveis',item_condition:'Usado - bom estado',city:'',state:'',whatsapp:'',instagram:''});
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);const {data}=await supabase.from('market_items').select('*').order('created_at',{ascending:false});setRows((data||[]) as Item[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 function chooseFile(f:File|null){setMessage('');if(!f){setFile(null);setPreview(null);return}if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setMessage('Use JPG, PNG ou WEBP.');return}if(f.size>10*1024*1024){setMessage('A imagem precisa ter no máximo 10 MB.');return}if(preview)URL.revokeObjectURL(preview);setFile(f);setPreview(URL.createObjectURL(f))}
 async function create(){if(!userId||!form.title.trim()||!form.price){setMessage('Preencha título e preço.');return}let urls:string[]=[];if(file){const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${userId}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('market').upload(path,file,{contentType:file.type,upsert:false});if(error){setMessage('Não foi possível enviar a imagem.');return}urls=[supabase.storage.from('market').getPublicUrl(path).data.publicUrl]}const {error}=await supabase.from('market_items').insert({seller_id:userId,title:form.title.trim(),description:form.description.trim()||null,image_urls:urls,price:Number(String(form.price).replace(',','.')),category:form.category,item_condition:form.item_condition,city:form.city.trim()||null,state:form.state.trim()||null,whatsapp:form.whatsapp.trim()||null,instagram:form.instagram.trim()||null,status:'available'});if(error){setMessage('Não foi possível publicar o anúncio.');return}setForm({title:'',description:'',price:'',category:'Colecionáveis',item_condition:'Usado - bom estado',city:'',state:'',whatsapp:'',instagram:''});setFile(null);setPreview(null);setShowForm(false);await load()}
 async function status(id:string,value:string){await supabase.from('market_items').update({status:value,updated_at:new Date().toISOString()}).eq('id',id);await load()}
 async function remove(id:string){if(!confirm('Excluir este anúncio?'))return;await supabase.from('market_items').delete().eq('id',id);await load()}
 const visible=rows.filter(i=>{const q=search.trim().toLowerCase();return(categoryFilter==='Todos'||i.category===categoryFilter)&&(!q||i.title.toLowerCase().includes(q)||(i.description||'').toLowerCase().includes(q)||(i.city||'').toLowerCase().includes(q))});
 function wa(value:string){const digits=value.replace(/\D/g,'');return digits?`https://wa.me/${digits}`:'#'}
 return <div className="mx-auto max-w-6xl px-3 sm:px-4"><div className="mb-5 flex flex-wrap items-end gap-3"><div><h1 className="text-2xl font-black">Mercado Geek</h1><p className="mt-1 text-sm text-slate-400">Itens usados, colecionáveis e oportunidades da comunidade.</p></div><button onClick={()=>setShowForm(v=>!v)} className="ml-auto rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold flex items-center gap-2"><Plus size={17}/>Anunciar item</button></div>
 {showForm&&<section className="mb-5 rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="grid gap-3 sm:grid-cols-2"><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Título do item" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="Preço (ex.: 150,00)" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><select value={form.category} onChange={e=>set('category',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3">{categories.map(c=><option key={c}>{c}</option>)}</select><select value={form.item_condition} onChange={e=>set('item_condition',e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft p-3"><option>Novo</option><option>Seminovo</option><option>Usado - ótimo estado</option><option>Usado - bom estado</option><option>Usado - com marcas</option></select><input value={form.city} onChange={e=>set('city',e.target.value)} placeholder="Cidade" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.state} onChange={e=>set('state',e.target.value)} placeholder="Estado/UF" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.whatsapp} onChange={e=>set('whatsapp',e.target.value)} placeholder="WhatsApp com DDI/DDD" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><input value={form.instagram} onChange={e=>set('instagram',e.target.value)} placeholder="Instagram" className="rounded-xl border border-geek-line bg-geek-soft p-3"/><textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Descrição" className="min-h-24 rounded-xl border border-geek-line bg-geek-soft p-3 sm:col-span-2"/></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>chooseFile(e.target.files?.[0]||null)}/><div className="mt-3"><button onClick={()=>fileRef.current?.click()} className="rounded-xl border border-geek-line px-3 py-2 text-sm flex items-center gap-2"><ImageIcon size={17}/>Adicionar foto</button></div>{preview&&<div className="mt-3 aspect-[4/3] max-w-sm overflow-hidden rounded-xl border border-geek-line bg-black/20"><img src={preview} alt="Prévia" className="h-full w-full object-contain"/></div>}{message&&<p className="mt-2 text-sm text-red-400">{message}</p>}<button onClick={create} className="mt-4 rounded-xl bg-geek-orange px-5 py-3 font-bold">Publicar anúncio</button></section>}
 <div className="mb-4 grid gap-3 sm:grid-cols-[1fr_auto]"><div className="flex items-center gap-2 rounded-xl border border-geek-line bg-geek-panel px-3"><Search size={16} className="text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar no Mercado Geek" className="w-full bg-transparent py-3 outline-none"/></div><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)} className="rounded-xl border border-geek-line bg-geek-panel px-3">{['Todos',...categories].map(c=><option key={c}>{c}</option>)}</select></div>
 {loading?<div className="py-20 grid place-items-center"><Loader2 className="animate-spin text-geek-orange"/></div>:visible.length===0?<div className="rounded-2xl border border-dashed border-geek-line bg-geek-panel p-10 text-center text-slate-400"><Store className="mx-auto mb-3 text-geek-orange"/>Nenhum item encontrado.</div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(i=><article key={i.id} className={`overflow-hidden rounded-2xl border border-geek-line bg-geek-panel ${i.status==='sold'?'opacity-60':''}`}><div className="aspect-[4/3] bg-black/20">{i.image_urls?.[0]?<img src={i.image_urls[0]} alt={i.title} className="h-full w-full object-contain"/>:<div className="h-full grid place-items-center text-slate-600"><Store size={36}/></div>}</div><div className="p-4"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h2 className="font-black">{i.title}</h2><p className="text-xs text-slate-500">{i.category||'Geek'} · {i.item_condition||'Condição não informada'}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${i.status==='sold'?'bg-red-500/10 text-red-300':i.status==='reserved'?'bg-yellow-500/10 text-yellow-300':'bg-emerald-500/10 text-emerald-300'}`}>{i.status==='sold'?'Vendido':i.status==='reserved'?'Reservado':'Disponível'}</span></div><p className="mt-3 text-xl font-black text-geek-orange">{Number(i.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p>{i.description&&<p className="mt-2 line-clamp-3 text-sm text-slate-400">{i.description}</p>}<p className="mt-2 text-xs text-slate-500">{[i.city,i.state].filter(Boolean).join(' / ')}</p>{i.seller_id===userId?<div className="mt-4 flex flex-wrap gap-2"><select value={i.status} onChange={e=>status(i.id,e.target.value)} className="rounded-xl border border-geek-line bg-geek-soft px-3 py-2 text-sm"><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></select><button onClick={()=>remove(i.id)} className="rounded-xl border border-red-500/30 px-3 py-2 text-red-300"><Trash2 size={16}/></button></div>:i.status!=='sold'?<div className="mt-4 flex gap-2">{i.whatsapp&&<a href={wa(i.whatsapp)} target="_blank" rel="noreferrer" className="rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold">WhatsApp</a>}{i.instagram&&<a href={`https://instagram.com/${i.instagram.replace('@','')}`} target="_blank" rel="noreferrer" className="rounded-xl border border-geek-line px-4 py-2 text-sm">Instagram</a>}</div>:null}</div></article>)}</div>}
 </div>;
}
