'use client';

import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { ArrowLeft, Copy, Gamepad2, Heart, IdCard, Loader2, MessageCircle, Share2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Profile={id:string;display_name:string;username:string|null;avatar_url:string|null;level:number;xp:number};
type CardData={title?:string;subtitle?:string;rarity?:string;atk?:number;def?:number;description?:string;category?:string;photo_url?:string};
type Post={id:string;author_id:string;content:string|null;image_url:string|null;video_url:string|null;category:string|null;post_type:string;card_data:CardData|null;created_at:string};
type Comment={id:string;author_id:string;content:string;created_at:string};

function GeekCard({post,author}:{post:Post;author:Profile|null}){
 const card=post.card_data||{};
 return <div className="mx-auto w-full max-w-[370px] overflow-hidden rounded-[28px] border-2 border-orange-400/55 bg-gradient-to-b from-[#28202f] to-[#101218] shadow-xl"><div className="flex items-center justify-between gap-3 border-b border-white/10 px-4 py-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.18em] text-orange-300">{card.rarity||'Raro'}</p><h2 className="truncate font-black">{card.title||author?.display_name||'Geek Card'}</h2></div><IdCard className="shrink-0 text-orange-300" size={20}/></div><div className="mx-3 mt-3 flex aspect-[3/4] items-center justify-center overflow-hidden rounded-2xl border border-white/10 bg-black/35">{(card.photo_url||post.image_url)?<img src={card.photo_url||post.image_url||''} alt="Geek Card" className="h-full w-full object-cover object-center"/>:<Gamepad2 className="text-slate-600"/>}</div><div className="p-4"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-orange-500/15 px-2 py-1 text-[10px] text-orange-300">{card.category||post.category||'Geek'}</span><span className="text-xs text-slate-400">Lv.{author?.level||1} · {author?.xp||0} XP</span></div>{card.subtitle&&<p className="mt-3 text-sm font-bold text-orange-100">{card.subtitle}</p>}<p className="mt-2 min-h-10 text-xs leading-5 text-slate-300">{card.description||post.content||'Meu Geek Card no GeekoPlay.'}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-red-500/10 p-3 text-center"><span className="text-[10px] text-red-300">ATK</span><p className="text-xl font-black">{card.atk??0}</p></div><div className="rounded-xl bg-cyan-500/10 p-3 text-center"><span className="text-[10px] text-cyan-300">DEF</span><p className="text-xl font-black">{card.def??0}</p></div></div><div className="mt-4 border-t border-white/10 pt-3 text-[10px] text-slate-500">@{author?.username||'geek'} · GeekoPlay</div></div></div>;
}

export function PostDetailClient({postId}:{postId:string}){
 const supabase=useMemo(()=>createClient(),[]);
 const [userId,setUserId]=useState<string|null>(null);const [post,setPost]=useState<Post|null>(null);const [author,setAuthor]=useState<Profile|null>(null);const [comments,setComments]=useState<Comment[]>([]);const [commentAuthors,setCommentAuthors]=useState<Record<string,Profile>>({});const [liked,setLiked]=useState(false);const [likeCount,setLikeCount]=useState(0);const [draft,setDraft]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');
 async function load(){
  setLoading(true);const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);
  const {data:p}=await supabase.from('posts').select('id,author_id,content,image_url,video_url,category,post_type,card_data,created_at').eq('id',postId).maybeSingle();
  if(!p){setPost(null);setLoading(false);return}
  const safe=p as Post;setPost(safe);
  const [{data:a},{data:likes},{data:c}]=await Promise.all([supabase.from('profiles').select('id,display_name,username,avatar_url,level,xp').eq('id',safe.author_id).maybeSingle(),supabase.from('likes').select('user_id').eq('post_id',postId),supabase.from('comments').select('id,author_id,content,created_at').eq('post_id',postId).order('created_at',{ascending:true})]);
  setAuthor((a||null) as Profile|null);setLikeCount((likes||[]).length);setLiked(!!user&&(likes||[]).some(row=>row.user_id===user.id));setComments((c||[]) as Comment[]);
  const ids=[...new Set((c||[]).map(row=>row.author_id))];if(ids.length){const {data:profiles}=await supabase.from('profiles').select('id,display_name,username,avatar_url,level,xp').in('id',ids);const map:Record<string,Profile>={};(profiles||[]).forEach((profile:Profile)=>map[profile.id]=profile);setCommentAuthors(map)}else setCommentAuthors({});setLoading(false);
 }
 useEffect(()=>{void load();const channel=supabase.channel(`post-detail-${postId}`).on('postgres_changes',{event:'*',schema:'public',table:'likes',filter:`post_id=eq.${postId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'comments',filter:`post_id=eq.${postId}`},()=>void load()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'posts',filter:`id=eq.${postId}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[postId,supabase]);
 async function toggleLike(){if(!userId)return;if(liked)await supabase.from('likes').delete().eq('post_id',postId).eq('user_id',userId);else await supabase.from('likes').insert({post_id:postId,user_id:userId});await load()}
 async function sendComment(){const text=draft.trim();if(!userId||!text)return;const {error}=await supabase.from('comments').insert({post_id:postId,author_id:userId,content:text});if(error){setMessage('Não foi possível comentar agora.');return}setDraft('');await load()}
 async function share(){const url=window.location.href;if(navigator.share){try{await navigator.share({title:'GeekoPlay',text:post?.post_type==='card'?'Veja este Geek Card no GeekoPlay':post?.content?.slice(0,120)||'Veja esta publicação no GeekoPlay',url})}catch{}}else{try{await navigator.clipboard.writeText(url);setMessage('Link copiado.')}catch{setMessage('Não foi possível copiar o link.')}}}
 if(loading)return <div className="grid place-items-center py-20"><Loader2 className="animate-spin text-geek-orange"/></div>;
 if(!post)return <div className="mx-auto max-w-2xl px-4 py-12 text-center"><h1 className="text-xl font-black">Publicação não encontrada</h1><p className="mt-2 text-sm text-slate-500">Ela pode ter sido removida ou não estar mais disponível.</p><Link href="/" className="mt-5 inline-flex rounded-xl bg-geek-orange px-4 py-2 text-sm font-bold">Voltar ao feed</Link></div>;
 return <div className="mx-auto max-w-2xl px-3 pb-10 sm:px-4"><Link href="/" className="mb-4 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/>Voltar ao feed</Link><article className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel"><header className="flex items-center gap-3 p-4">{author?.avatar_url?<img src={author.avatar_url} alt="" className="h-10 w-10 rounded-full object-cover object-center"/>:<div className="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-orange-400 to-purple-600 text-sm font-black">{author?.display_name?.slice(0,1).toUpperCase()||'G'}</div>}<div className="min-w-0 flex-1"><Link href={author?`/perfil/${author.id}`:'#'} className="block truncate text-sm font-black hover:text-orange-300">{author?.display_name||'Geek'}</Link><p className="truncate text-xs text-slate-500">@{author?.username||'geek'} · {new Date(post.created_at).toLocaleString('pt-BR')}</p></div></header>{post.post_type==='card'?<GeekCard post={post} author={author}/>:<>{post.content&&<p className="px-4 pb-4 whitespace-pre-wrap break-words text-sm leading-6 text-slate-200">{post.content}</p>}{post.image_url&&<div className="flex max-h-[75vh] min-h-24 items-center justify-center overflow-hidden bg-black/30"><img src={post.image_url} alt="Publicação" className="block h-auto max-h-[75vh] w-auto max-w-full object-contain object-center"/></div>}{post.video_url&&<div className="flex max-h-[75vh] items-center justify-center bg-black"><video src={post.video_url} controls playsInline preload="metadata" className="block max-h-[75vh] w-full object-contain"/></div>}</>}<div className="flex items-center border-t border-geek-line"><button onClick={toggleLike} className={`flex flex-1 items-center justify-center gap-2 py-3 text-sm ${liked?'text-red-400':'text-slate-400'}`}><Heart size={18} fill={liked?'currentColor':'none'}/>{likeCount}</button><div className="flex flex-1 items-center justify-center gap-2 py-3 text-sm text-slate-400"><MessageCircle size={18}/>{comments.length}</div><button onClick={share} className="flex flex-1 items-center justify-center gap-2 py-3 text-sm text-slate-400"><Share2 size={18}/><span className="hidden sm:inline">Compartilhar</span></button></div></article>
 <section className="mt-4 rounded-2xl border border-geek-line bg-geek-panel p-4"><h2 className="font-black">Comentários</h2><div className="mt-3 flex gap-2"><input value={draft} maxLength={1500} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sendComment()}} placeholder="Escreva um comentário..." className="min-w-0 flex-1 rounded-xl border border-geek-line bg-geek-soft px-3 py-2 text-sm outline-none"/><button onClick={sendComment} disabled={!draft.trim()} className="rounded-xl bg-geek-orange px-4 text-sm font-bold disabled:opacity-40">Enviar</button></div>{message&&<p className="mt-2 text-xs text-slate-400">{message}</p>}<div className="mt-4 space-y-3">{comments.length===0?<p className="py-5 text-center text-sm text-slate-500">Ainda não há comentários.</p>:comments.map(comment=>{const person=commentAuthors[comment.author_id];return <div key={comment.id} className="flex gap-3 rounded-xl bg-geek-soft p-3">{person?.avatar_url?<img src={person.avatar_url} alt="" className="h-8 w-8 shrink-0 rounded-full object-cover object-center"/>:<div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gradient-to-br from-orange-400 to-purple-600 text-[10px] font-black">{person?.display_name?.slice(0,1).toUpperCase()||'G'}</div>}<div className="min-w-0"><p className="text-xs font-bold">{person?.display_name||'Geek'} <span className="font-normal text-slate-500">· {new Date(comment.created_at).toLocaleString('pt-BR')}</span></p><p className="mt-1 whitespace-pre-wrap break-words text-sm text-slate-300">{comment.content}</p></div></div>})}</div></section>
 </div>;
}
