'use client';

import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { CalendarDays,Image as ImageIcon,LibraryBig,Loader2,Store,Trash2,Trophy,Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Tab='publicacoes'|'curtidas'|'eventos'|'comunidades'|'colecao'|'mercado'|'sobre';
type Post={id:string;content:string|null;image_url:string|null;video_url:string|null;category:string|null;created_at:string};
type Event={id:string;title:string;cover_url:string|null;starts_at:string;city:string|null;state:string|null};
type EventPlan={id:string;title:string;event_date:string;location:string;note:string|null;shared_post_id:string|null};
type Community={id:string;name:string;cover_url:string|null;category:string|null;description:string|null};
type Item={id:string;title:string;image_url:string|null;status:string;category:string|null};
type MarketItem={id:string;title:string;image_urls:string[];price:number;status:string;category:string|null;city:string|null;state:string|null};
type Profile={bio:string|null;city:string|null;favorite_categories:string[]};
type AchievementStats={unlocked:number;total:number};
const tabs:[string,Tab][]=[['Publicações','publicacoes'],['Curtidas','curtidas'],['Eventos','eventos'],['Comunidades','comunidades'],['Coleção','colecao'],['Mercado','mercado'],['Sobre','sobre']];

export function ProfileTabs(){
 const supabase=useMemo(()=>createClient(),[]);const [tab,setTab]=useState<Tab>('publicacoes');const [loading,setLoading]=useState(true);const [posts,setPosts]=useState<Post[]>([]);const [likedPosts,setLikedPosts]=useState<Post[]>([]);const [events,setEvents]=useState<Event[]>([]);const [eventPlans,setEventPlans]=useState<EventPlan[]>([]);const [communities,setCommunities]=useState<Community[]>([]);const [items,setItems]=useState<Item[]>([]);const [marketItems,setMarketItems]=useState<MarketItem[]>([]);const [profile,setProfile]=useState<Profile|null>(null);const [achievementStats,setAchievementStats]=useState<AchievementStats>({unlocked:0,total:0});const [message,setMessage]=useState('');

 async function load(){
  setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}
  const [{data:ownPosts},{data:likes},{data:attendance},{data:plans},{data:memberships},{data:collection},{data:market},{data:p},{count:achievementTotal},{count:achievementUnlocked}]=await Promise.all([
   supabase.from('posts').select('id,content,image_url,video_url,category,created_at').eq('author_id',user.id).order('created_at',{ascending:false}).limit(50),
   supabase.from('likes').select('post_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50),
   supabase.from('event_attendees').select('event_id').eq('user_id',user.id).in('status',['going','confirmed']),
   supabase.from('user_event_plans').select('id,title,event_date,location,note,shared_post_id').eq('user_id',user.id).order('event_date',{ascending:false}),
   supabase.from('community_members').select('community_id').eq('user_id',user.id),
   supabase.from('collection_items').select('id,title,image_url,status,category').eq('owner_id',user.id).order('created_at',{ascending:false}).limit(30),
   supabase.from('market_items').select('id,title,image_urls,price,status,category,city,state').eq('seller_id',user.id).order('created_at',{ascending:false}).limit(30),
   supabase.from('profiles').select('bio,city,favorite_categories').eq('id',user.id).maybeSingle(),
   supabase.from('achievement_definitions').select('id',{count:'exact',head:true}),
   supabase.from('user_achievements').select('achievement_id',{count:'exact',head:true}).eq('user_id',user.id).not('unlocked_at','is',null)
  ]);
  setPosts((ownPosts||[]) as Post[]);setEventPlans((plans||[]) as EventPlan[]);setItems((collection||[]) as Item[]);setMarketItems((market||[]) as MarketItem[]);setProfile((p||null) as Profile|null);setAchievementStats({unlocked:achievementUnlocked||0,total:achievementTotal||0});
  const likeIds=(likes||[]).map(x=>x.post_id);if(likeIds.length){const {data}=await supabase.from('posts').select('id,content,image_url,video_url,category,created_at').in('id',likeIds).limit(50);setLikedPosts((data||[]) as Post[])}else setLikedPosts([]);
  const eventIds=[...new Set((attendance||[]).map(x=>x.event_id))];if(eventIds.length){const {data}=await supabase.from('events').select('id,title,cover_url,starts_at,city,state').in('id',eventIds).order('starts_at',{ascending:false});setEvents((data||[]) as Event[])}else setEvents([]);
  const communityIds=(memberships||[]).map(x=>x.community_id);if(communityIds.length){const {data}=await supabase.from('communities').select('id,name,cover_url,category,description').in('id',communityIds);setCommunities((data||[]) as Community[])}else setCommunities([]);setLoading(false);
 }
 useEffect(()=>{void load()},[supabase]);
 async function removePlan(plan:EventPlan){if(!confirm(`Remover "${plan.title}" dos seus eventos?`))return;setMessage('');if(plan.shared_post_id)await supabase.from('posts').delete().eq('id',plan.shared_post_id);const {error}=await supabase.from('user_event_plans').delete().eq('id',plan.id);setMessage(error?'Não foi possível remover o evento.':'Evento removido.');await load()}

 const PostGrid=({rows}:{rows:Post[]})=><div className="grid gap-3 sm:grid-cols-2">{rows.length===0?<Empty text="Nenhuma publicação por aqui ainda."/>:rows.map(post=><Link href={`/publicacao/${post.id}`} key={post.id} className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel">{post.image_url&&<div className="flex max-h-80 items-center justify-center bg-black/25"><img src={post.image_url} alt="" className="h-auto max-h-80 w-auto max-w-full object-contain object-center"/></div>}{post.video_url&&<div className="flex max-h-80 items-center justify-center bg-black"><video src={post.video_url} controls playsInline preload="metadata" className="max-h-80 max-w-full object-contain object-center"/></div>}<div className="p-4">{post.category&&<span className="rounded-full bg-orange-500/10 px-2 py-1 text-[10px] text-orange-300">{post.category}</span>}{post.content&&<p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm text-slate-300">{post.content}</p>}</div></Link>)}</div>;

 const achievementPct=achievementStats.total?Math.round((achievementStats.unlocked/achievementStats.total)*100):0;
 return <section className="mx-auto mt-4 w-full max-w-4xl px-3 pb-8 sm:px-5"><div className="overflow-x-auto border-b border-geek-line"><div className="flex min-w-max gap-1">{tabs.map(([label,value])=><button key={value} onClick={()=>setTab(value)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab===value?'border-geek-orange text-orange-300':'border-transparent text-slate-400'}`}>{label}</button>)}</div></div>{message&&<div className="mt-4 rounded-xl border border-geek-line bg-geek-panel px-4 py-3 text-sm text-slate-300">{message}</div>}<div className="pt-4">{loading?<div className="grid place-items-center py-16"><Loader2 className="animate-spin text-geek-orange"/></div>:<>
  {tab==='publicacoes'&&<PostGrid rows={posts}/>} {tab==='curtidas'&&<PostGrid rows={likedPosts}/>} 
  {tab==='eventos'&&<div className="space-y-5"><section><div className="mb-3"><h3 className="font-black">Eventos oficiais confirmados</h3><p className="text-xs text-slate-500">Eventos cadastrados pela equipe GeekoPlay.</p></div>{events.length===0?<Empty text="Você ainda não confirmou presença em eventos oficiais."/>:<div className="grid gap-3 sm:grid-cols-2">{events.map(e=><Link href={`/eventos/${e.id}`} key={e.id} className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel">{e.cover_url?<div className="flex aspect-[16/7] items-center justify-center overflow-hidden bg-black/20"><img src={e.cover_url} alt="" className="block h-auto max-h-full w-auto max-w-full object-contain object-center"/></div>:<div className="grid aspect-[16/7] place-items-center bg-geek-soft"><CalendarDays className="text-geek-orange"/></div>}<div className="p-4"><b>{e.title}</b><p className="mt-1 text-xs text-slate-500">{new Date(e.starts_at).toLocaleDateString('pt-BR')} · {[e.city,e.state].filter(Boolean).join(' / ')||'Local a definir'}</p></div></Link>)}</div>}</section><section><div className="mb-3"><h3 className="font-black">Eventos que eu vou</h3><p className="text-xs text-slate-500">Planos que você adicionou manualmente no feed.</p></div>{eventPlans.length===0?<Empty text="Você ainda não adicionou eventos próprios."/>:<div className="grid gap-3 sm:grid-cols-2">{eventPlans.map(plan=><article key={plan.id} className="rounded-2xl border border-geek-line bg-geek-panel p-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-orange-500/10"><CalendarDays size={20} className="text-geek-orange"/></div><div className="min-w-0 flex-1"><b className="block break-words">{plan.title}</b><p className="mt-1 text-xs text-slate-500">{new Date(plan.event_date).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</p><p className="mt-1 break-words text-xs text-slate-400">📍 {plan.location}</p>{plan.note&&<p className="mt-2 line-clamp-3 text-xs leading-5 text-slate-400">{plan.note}</p>}</div><button onClick={()=>void removePlan(plan)} className="rounded-lg p-2 text-red-300 hover:bg-red-500/10" aria-label="Remover evento"><Trash2 size={16}/></button></div>{plan.shared_post_id&&<Link href={`/publicacao/${plan.shared_post_id}`} className="mt-3 inline-flex text-xs font-bold text-geek-orange">Ver publicação no feed</Link>}</article>)}</div>}</section></div>}
  {tab==='comunidades'&&(communities.length===0?<Empty text="Você ainda não participa de comunidades."/>:<div className="grid gap-3 sm:grid-cols-2">{communities.map(c=><Link href={`/comunidades/${c.id}`} key={c.id} className="flex min-w-0 gap-3 rounded-2xl border border-geek-line bg-geek-panel p-4">{c.cover_url?<div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-black/20"><img src={c.cover_url} alt="" className="block h-auto max-h-full w-auto max-w-full object-contain object-center"/></div>:<div className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-geek-soft"><Users className="text-geek-orange"/></div>}<div className="min-w-0"><b className="block truncate">{c.name}</b><p className="text-xs text-orange-300">{c.category||'Comunidade'}</p>{c.description&&<p className="mt-1 line-clamp-2 text-xs text-slate-500">{c.description}</p>}</div></Link>)}</div>)}
  {tab==='colecao'&&(items.length===0?<Empty text="Sua coleção ainda está vazia."/>:<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{items.map(item=><Link href={`/colecao/${item.id}`} key={item.id} className="overflow-hidden rounded-2xl border border-geek-line bg-geek-panel">{item.image_url?<div className="flex aspect-[4/5] items-center justify-center overflow-hidden bg-black/20"><img src={item.image_url} alt="" className="block h-auto max-h-full w-auto max-w-full object-contain object-center"/></div>:<div className="grid aspect-[4/5] place-items-center bg-geek-soft"><LibraryBig className="text-geek-orange"/></div>}<div className="p-3"><b className="block truncate text-sm">{item.title}</b><p className="text-[10px] text-slate-500">{item.status} · {item.category||'Geek'}</p></div></Link>)}</div>)}
  {tab==='mercado'&&(marketItems.length===0?<Empty text="Você ainda não anunciou itens no Mercado Geek."/>:<div className="grid grid-cols-2 gap-2 sm:gap-3 md:grid-cols-3">{marketItems.map(item=><Link href={`/mercado/${item.id}`} key={item.id} className={`min-w-0 overflow-hidden rounded-2xl border border-geek-line bg-geek-panel ${item.status==='sold'?'opacity-60':''}`}><div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden bg-black/20">{item.image_urls?.[0]?<img src={item.image_urls[0]} alt="" className="block h-auto max-h-full w-auto max-w-full object-contain object-center"/>:<Store className="text-geek-orange"/>}</div><div className="min-w-0 p-3"><b className="block truncate text-sm">{item.title}</b><p className="mt-1 truncate text-sm font-black text-geek-orange">{Number(item.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p></div></Link>)}</div>)}
  {tab==='sobre'&&<div className="space-y-4"><div className="rounded-2xl border border-geek-line bg-geek-panel p-5"><h3 className="font-black">Sobre</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-400">{profile?.bio||'Este geek ainda não escreveu uma bio.'}</p>{profile?.city&&<p className="mt-3 text-sm text-slate-400">📍 {profile.city}</p>}{!!profile?.favorite_categories?.length&&<div className="mt-4 flex flex-wrap gap-2">{profile.favorite_categories.map(x=><span key={x} className="rounded-full bg-geek-soft px-3 py-1.5 text-xs">{x}</span>)}</div>}</div><Link href="/conquistas" className="block rounded-2xl border border-orange-500/25 bg-orange-500/5 p-5 transition hover:border-orange-500/50 hover:bg-orange-500/10"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-orange-500/10 text-orange-300"><Trophy size={21}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-black">Vitrine de conquistas</h3><p className="mt-1 text-xs text-slate-400">Seu progresso dentro do universo GeekoPlay.</p></div><b className="text-xl text-orange-300">{achievementStats.unlocked}/{achievementStats.total}</b></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-geek-soft"><div className="h-full rounded-full bg-geek-orange transition-all" style={{width:`${achievementPct}%`}}/></div><div className="mt-2 flex items-center justify-between gap-3 text-xs text-slate-500"><span>{achievementPct}% concluído</span><span className="font-semibold text-orange-300">Ver conquistas →</span></div></div></div></Link></div>}
 </>}</div></section>;
}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-2xl border border-dashed border-geek-line bg-geek-panel p-10 text-center text-slate-500"><ImageIcon className="mx-auto mb-2 text-geek-orange"/>{text}</div>}
