'use client';

import { useEffect,useMemo,useState } from 'react';
import { Plus,X,ChevronLeft,ChevronRight,Loader2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { ImageCropper } from '@/components/image-cropper';
import { PhotoSourcePicker } from '@/components/photo-source-picker';

type Pulse={id:string;author_id:string;image_url:string;caption:string|null;fandom:string|null;expires_at:string;created_at:string};
type Profile={id:string;display_name:string;avatar_url:string|null};
const PULSE_MS=5000;

export function PulseStrip(){
 const supabase=useMemo(()=>createClient(),[]);const [userId,setUserId]=useState<string|null>(null);const [pulses,setPulses]=useState<Pulse[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [viewerIndex,setViewerIndex]=useState<number|null>(null);const [progressKey,setProgressKey]=useState(0);const [creating,setCreating]=useState(false);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<string|null>(null);const [cropSource,setCropSource]=useState<File|null>(null);const [caption,setCaption]=useState('');const [fandom,setFandom]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('');

 async function load(){const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);const {data:rows}=await supabase.from('pulses').select('id,author_id,image_url,caption,fandom,expires_at,created_at').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(50);const safe=(rows||[]) as Pulse[];setPulses(safe);const ids=[...new Set(safe.map(p=>p.author_id))];if(ids.length){const {data:people}=await supabase.from('profiles').select('id,display_name,avatar_url').in('id',ids);const map:Record<string,Profile>={};(people||[]).forEach((p:Profile)=>map[p.id]=p);setProfiles(map)}else setProfiles({})}
 useEffect(()=>{void load();const channel=supabase.channel('pulses-live').on('postgres_changes',{event:'*',schema:'public',table:'pulses'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[supabase]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('criar')==='pulse')setCreating(true)},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);

 function choose(fileValue:File|null){setError('');if(!fileValue){setCropSource(null);return}if(!['image/jpeg','image/png','image/webp'].includes(fileValue.type)){setError('Use uma imagem JPG, PNG ou WEBP.');return}if(fileValue.size>10*1024*1024){setError('A imagem precisa ter no máximo 10 MB.');return}setCropSource(fileValue)}
 function clearPhoto(){if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview(null);setCropSource(null)}
 function confirmCrop(cropped:File,previewUrl:string){if(preview)URL.revokeObjectURL(preview);setFile(cropped);setPreview(previewUrl);setCropSource(null)}
 async function save(){if(!userId||!file)return;setSaving(true);setError('');let uploadedPath:string|null=null;try{const path=`${userId}/${crypto.randomUUID()}.webp`;uploadedPath=path;const {error:uploadError}=await supabase.storage.from('pulses').upload(path,file,{contentType:'image/webp',cacheControl:'3600'});if(uploadError)throw uploadError;const {data:urlData}=supabase.storage.from('pulses').getPublicUrl(path);const {error:insertError}=await supabase.from('pulses').insert({author_id:userId,image_url:urlData.publicUrl,caption:caption.trim()||null,fandom:fandom.trim()||null,expires_at:new Date(Date.now()+24*60*60*1000).toISOString()});if(insertError)throw insertError;clearPhoto();setCaption('');setFandom('');setCreating(false);await load()}catch{if(uploadedPath)await supabase.storage.from('pulses').remove([uploadedPath]);setError('Não foi possível publicar o Pulse. Nenhuma cópia incompleta foi mantida; tente novamente.')}finally{setSaving(false)}}

 const groups=Object.values(pulses.reduce((acc,p)=>{(acc[p.author_id]||=[]).push(p);return acc},{} as Record<string,Pulse[]>));const flattened=groups.flat();const active=viewerIndex!==null?flattened[viewerIndex]:null;const author=active?profiles[active.author_id]:null;
 function openAt(index:number){setViewerIndex(index);setProgressKey(v=>v+1)}
 function previous(){if(viewerIndex===null)return;openAt(Math.max(0,viewerIndex-1))}
 function next(){if(viewerIndex===null)return;if(viewerIndex<flattened.length-1)openAt(viewerIndex+1);else setViewerIndex(null)}
 useEffect(()=>{if(viewerIndex===null)return;const timer=window.setTimeout(next,PULSE_MS);return()=>window.clearTimeout(timer)},[viewerIndex,flattened.length]);
 useEffect(()=>{function onKey(event:KeyboardEvent){if(viewerIndex===null)return;if(event.key==='ArrowRight')next();if(event.key==='ArrowLeft')previous();if(event.key==='Escape')setViewerIndex(null)}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[viewerIndex,flattened.length]);

 return <>
  {cropSource&&<ImageCropper file={cropSource} aspect={9/16} title="Ajustar imagem do Pulse" outputWidth={1080} onCancel={()=>setCropSource(null)} onConfirm={confirmCrop}/>}<div className="mx-auto mb-4 max-w-2xl px-3 sm:px-4"><div className="overflow-x-auto pb-2"><div className="flex min-w-max gap-3"><button onClick={()=>setCreating(true)} className="flex w-20 flex-col items-center gap-2 text-xs text-slate-300"><span className="relative grid h-16 w-16 place-items-center rounded-full border-2 border-dashed border-geek-orange bg-geek-panel"><Plus className="text-geek-orange"/></span><span className="max-w-20 truncate">Seu Pulse</span></button>{groups.map(group=>{const first=group[0];const p=profiles[first.author_id];const firstIndex=flattened.findIndex(x=>x.id===first.id);return <button key={first.author_id} onClick={()=>openAt(firstIndex)} className="flex w-20 flex-col items-center gap-2 text-xs text-slate-300"><span className="h-16 w-16 rounded-full bg-gradient-to-br from-orange-400 via-pink-500 to-purple-600 p-[2px]"><span className="block h-full w-full rounded-full bg-geek-bg p-[2px]"><span className="block h-full w-full overflow-hidden rounded-full bg-geek-soft">{p?.avatar_url?<img src={p.avatar_url} alt="" className="h-full w-full object-cover object-center"/>:<img src={first.image_url} alt="" className="h-full w-full object-cover object-center"/>}</span></span></span><span className="max-w-20 truncate">{p?.display_name||'Geek'}</span></button>})}</div></div></div>

  {creating&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/80 p-3 sm:p-6"><div className="w-full max-w-md rounded-3xl border border-geek-line bg-[#171b22] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Criar Pulse</h2><p className="text-xs text-slate-400">Imagem final 9:16. Duração: 24 horas.</p></div><button onClick={()=>{setCreating(false);clearPhoto()}} className="rounded-full p-2 hover:bg-geek-soft"><X/></button></div>{preview?<div className="mt-4"><div className="flex max-h-[55vh] aspect-[9/16] w-full items-center justify-center overflow-hidden rounded-2xl border border-geek-line bg-black/20"><img src={preview} alt="Prévia do Pulse" className="h-full w-full object-cover object-center"/></div><div className="mt-2 grid grid-cols-2 gap-2"><PhotoSourcePicker onSelect={choose} cameraFacing="environment" label="Trocar foto" className="rounded-xl border border-geek-line py-2 text-xs font-semibold"/><button onClick={clearPhoto} className="rounded-xl border border-geek-line py-2 text-xs text-slate-400">Remover imagem</button></div></div>:<PhotoSourcePicker onSelect={choose} cameraFacing="environment" label="Carregar ou tirar uma foto" className="mt-4 flex max-h-[55vh] aspect-[9/16] w-full items-center justify-center rounded-2xl border border-dashed border-geek-line bg-black/20 px-5 text-center text-sm font-semibold text-slate-400"/>}<p className="mt-2 text-xs leading-5 text-slate-500">Ao escolher ou tirar a foto, você pode dar zoom, reposicionar e confirmar o recorte. A mídia nunca é esticada ou deformada.</p><input value={caption} onChange={e=>setCaption(e.target.value)} maxLength={220} placeholder="Legenda (opcional)" className="mt-3 w-full rounded-xl border border-geek-line bg-geek-soft px-3 py-3 text-sm outline-none"/><input value={fandom} onChange={e=>setFandom(e.target.value)} maxLength={80} placeholder="Fandom/categoria (opcional)" className="mt-2 w-full rounded-xl border border-geek-line bg-geek-soft px-3 py-3 text-sm outline-none"/>{error&&<p className="mt-2 text-xs text-red-400">{error}</p>}<button onClick={()=>void save()} disabled={!file||saving} className="mt-4 w-full rounded-xl bg-geek-orange py-3 font-bold disabled:opacity-50">{saving?<span className="inline-flex items-center gap-2"><Loader2 size={16} className="animate-spin"/>Publicando...</span>:'Publicar Pulse'}</button></div></div>}

  {active&&viewerIndex!==null&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/95 p-0 sm:p-5"><div className="relative flex h-full w-full items-center justify-center overflow-hidden bg-black sm:h-[90vh] sm:max-w-md sm:rounded-3xl"><img src={active.image_url} alt="Pulse" className="h-auto max-h-full w-auto max-w-full object-contain object-center"/><div className="absolute inset-x-0 top-0 bg-gradient-to-b from-black/85 to-transparent p-4 pt-4"><div className="flex gap-1">{flattened.map((pulse,index)=><span key={pulse.id} className="h-1 flex-1 overflow-hidden rounded-full bg-white/25">{index<viewerIndex?<span className="block h-full w-full bg-white"/>:index===viewerIndex?<span key={`${pulse.id}-${progressKey}`} className="block h-full origin-left bg-white" style={{animation:`pulseProgress ${PULSE_MS}ms linear forwards`}}/>:null}</span>)}</div><div className="mt-3 flex items-center gap-3"><div className="h-9 w-9 overflow-hidden rounded-full bg-geek-soft">{author?.avatar_url&&<img src={author.avatar_url} alt="" className="h-full w-full object-cover object-center"/>}</div><div><b className="text-sm">{author?.display_name||'Geek'}</b>{active.fandom&&<p className="text-[11px] text-white/70">{active.fandom}</p>}</div><button onClick={()=>setViewerIndex(null)} className="ml-auto rounded-full bg-black/30 p-2" aria-label="Fechar Pulse"><X size={20}/></button></div></div>{active.caption&&<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent px-5 pb-8 pt-20 text-center text-sm">{active.caption}</div>}<button onClick={previous} disabled={viewerIndex===0} className="absolute left-2 top-1/2 -translate-y-1/2 rounded-full bg-black/40 p-2 disabled:opacity-20" aria-label="Pulse anterior"><ChevronLeft/></button><button onClick={next} className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full bg-black/40 p-2" aria-label="Próximo Pulse"><ChevronRight/></button><button onClick={previous} disabled={viewerIndex===0} className="absolute inset-y-20 left-0 w-1/3 opacity-0" aria-label="Voltar Pulse"/><button onClick={next} className="absolute inset-y-20 right-0 w-1/3 opacity-0" aria-label="Avançar Pulse"/></div></div>}
  <style jsx global>{`@keyframes pulseProgress{from{transform:scaleX(0)}to{transform:scaleX(1)}}`}</style>
 </>;
}