-- GeekoPlay: rastreamento opcional de localização durante eventos presenciais.
-- Mantém no repositório o mesmo schema/policies já aplicados em produção.

create table if not exists public.event_location_samples (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  latitude double precision not null check (latitude >= -90 and latitude <= 90),
  longitude double precision not null check (longitude >= -180 and longitude <= 180),
  accuracy_m double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists event_location_samples_event_time_idx
  on public.event_location_samples(event_id, recorded_at desc);

create index if not exists event_location_samples_user_event_idx
  on public.event_location_samples(user_id, event_id, recorded_at desc);

alter table public.event_location_samples enable row level security;

drop policy if exists "location samples own insert during event" on public.event_location_samples;
create policy "location samples own insert during event"
on public.event_location_samples
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.event_attendees a
    where a.event_id = event_location_samples.event_id
      and a.user_id = (select auth.uid())
      and a.status in ('going','confirmed')
  )
  and exists (
    select 1
    from public.events e
    where e.id = event_location_samples.event_id
      and e.is_online = false
      and now() >= e.starts_at - interval '1 hour'
      and now() <= coalesce(e.ends_at, e.starts_at + interval '24 hours') + interval '1 hour'
  )
);

drop policy if exists "location samples own read or admin" on public.event_location_samples;
create policy "location samples own read or admin"
on public.event_location_samples
for select
to authenticated
using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "location samples own delete or admin" on public.event_location_samples;
create policy "location samples own delete or admin"
on public.event_location_samples
for delete
to authenticated
using ((select auth.uid()) = user_id or public.is_admin());
